---
apiVersion: "isovalent.com/v1alpha1"
kind: PrivateNetworkNodeAttachment
metadata:
  name: "{{ .Network }}"
spec:
  privateNetworkRef:
    name: "{{ .Network }}"
  attachments:
  {{- range .Attachments }}
  - interface: "{{ .Interface }}"
  {{- if ne .VlanID 0 }}
    vlanID: {{ .VlanID }}
  {{- end }}
  {{- end }}
