apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: "{{ .Name }}"
  namespace: "{{ .TestNamespace }}"
  labels:
    app.kubernetes.io/part-of: cilium-cli-privnet
    {{- if .ID }}
    vmID: {{ .ID }}
    {{- end }}
    {{- with .PlanID }}
    plan: {{ . }}
    {{- end }}
spec:
  runStrategy: Always
  template:
    metadata:
      name: "{{ .Name }}"
      labels:
        name: "{{ .Name }}"
        kind: "{{ .Kind }}"
      {{- if .NeedsAnnotation }}
      annotations:
        privnet.isovalent.com/network-attachment: |-
          {{ formatPrimaryNetworkAttachment .Interfaces | indent 10 }}
        {{- with ( formatSecondaryNetworkAttachments .Interfaces ) }}
        privnet.isovalent.com/secondary-network-attachments: |-
          {{ . | indent 10 }}
        {{- end }}
      {{- end }}
    spec:
  {{- if .Affinity.Type }}
      affinity:
  {{- if eq .Affinity.Type "same-node" }}
        podAffinity:
  {{- else }}
        podAntiAffinity:
  {{- end }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - {{ .Affinity.Target }}
              topologyKey: kubernetes.io/hostname
  {{- end }}
      dnsPolicy: None
      dnsConfig:
        nameservers:
        {{- range .Interfaces }}
        {{- if .DNSServer.IsValid }}
        - {{ .DNSServer }}
        {{- end }}
        {{- end }}
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          - cdrom:
              bus: sata
            name: echoserver
          interfaces:
          {{- range $index, $iface := .Interfaces }}
          - name: eth{{ $index }}
            macAddress: {{ $iface.MAC }}
            binding:
              name: isovalent-networking
          {{- end }}
          rng: {}
        resources:
          requests:
            memory: 256M
      networks:
      {{- range $index, $iface := .Interfaces }}
      - name: eth{{ $index }}
        {{- if $iface.NAD }}
        multus:
          networkName: "{{ $.TestNamespace }}/{{ $iface.NAD }}"
          {{- if eq $index 0 }}
          default: true
          {{- end }}
        {{- else }}
        pod: {}
        {{- end }}
      {{- end }}
      readinessProbe:
        exec:
          command:
          - /run/scripts/ready.sh
        failureThreshold: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: "{{ .VMImage }}"
        name: containerdisk
      - configMap:
          name: {{ .ScriptConfigMap }}
          volumeLabel: echoserver
        name: echoserver
      - cloudInitNoCloud:
          secretRef:
            name: {{ .Name }}-cloud-init
          networkDataSecretRef:
            name: {{ .Name }}-cloud-init
        name: cloudinitdisk
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Name }}-cloud-init"
  namespace: "{{ .TestNamespace }}"
  labels:
    app.kubernetes.io/part-of: cilium-cli-privnet
stringData:
  userData: |
    #cloud-config
    password: alpine
    chpasswd: { expire: False }
    manage_etc_hosts: true
    mounts:
    - [ "/dev/disk/by-label/echoserver", "/mnt/scripts", "iso9660", "ro,nofail" ]
    write_files:
    - content: |
        #! /bin/sh -e

        case $IFACE in
        {{- range $index, $iface := .Interfaces }}
          eth{{ $index }})
            {{- range $iface.Routes }}
            ip {{ if .Destination.Addr.Is4 }}-4{{ else }}-6{{ end }} route add {{ .Destination }}
              {{- if .Gateway.IsValid }} via {{ .Gateway }}{{ end }} dev eth{{ $index }}
            {{- end }}
            ;;
        {{- end }}
        esac
      path: /etc/network/if-up.d/routes
      permissions: '0755'
    - content: |
        #!/sbin/openrc-run

        description="Serve http server echoing client IP"
        command="/usr/bin/python3"
        command_args="/mnt/scripts/echoserver.py"
        pidfile="/run/echoserver.pid"
        supervisor="supervise-daemon"
        command_background="yes"

        depend() {
            need localmount
            need net
        }

        start_pre() {
            export CILIUM_PRIVNET_NETWORK={{ ( index .Interfaces 0 ).Network }}
            export CILIUM_PRIVNET_PORT={{ .ServePort }}
        }
      path: /etc/init.d/echoserver
      permissions: '0755'
    - content: |
        #! /bin/sh -e

        # Check whether the hostname has been set correctly.
        [ $(hostname) = "{{ .Name }}" ]

        # Check whether the echo server is running.
        curl --fail --max-time 1 localhost:{{ .ServePort }}
      path: /run/scripts/ready.sh
      permissions: '0755'
    runcmd:
    # The script configuring the routes is written after starting the
    # networking service the first time. Hence, we need to restart it.
    - [rc-service, networking, restart]
    - [rc-service, echoserver, start]
    - [rc-update, add, echoserver]
  networkData: |
    version: 2
    ethernets:
    {{- range $index, $iface := .Interfaces }}
      eth{{ $index }}:
        {{- /* The subnet is set only if DHCP is enabled. */}}
        {{- if $iface.Subnet }}
        dhcp4: true
        {{- if $iface.IPv6.IsValid }}
        addresses:
          - {{ $iface.IPv6 }}
        {{- end }}
        {{- else }}
        addresses:
          {{- if $iface.IPv4.IsValid }}
          - {{ $iface.IPv4 }}
          {{- end }}
          {{- if $iface.IPv6.IsValid }}
          - {{ $iface.IPv6 }}
          {{- end }}
        {{- if $iface.DNSServer.IsValid }}
        nameservers:
          addresses: [ {{ $iface.DNSServer }} ]
        {{- end }}
        {{- end }}
    {{- end }}
