frr defaults datacenter
hostname tor
log file /tmp/frr.log
!
debug bgp neighbor-events
debug bgp updates in
debug bgp updates out
debug bgp zebra
!
vrf vrf1
 vni 100
exit-vrf
!
vrf vrf2
 vni 200
exit-vrf
!
router bgp 65000
 bgp router-id 172.0.0.1
 neighbor net0 interface remote-as 65000
 neighbor net1 interface remote-as 65000
 neighbor net2 interface remote-as 65000
 !
 neighbor EVPN_PEERS peer-group
 neighbor EVPN_PEERS remote-as 65000
 bgp listen range 100.64.1.0/24 peer-group EVPN_PEERS
 !
 address-family ipv4 unicast
  network 100.64.0.1/32
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor EVPN_PEERS activate
  advertise-all-vni
 exit-address-family
exit
!
router bgp 65000 vrf vrf1
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family ipv6 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  advertise ipv6 unicast
 exit-address-family
exit
!
router bgp 65000 vrf vrf2
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family ipv6 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  advertise ipv6 unicast
 exit-address-family
exit
