// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIsovalentCoreVRFs implements IsovalentCoreVRFInterface
type fakeIsovalentCoreVRFs struct {
	*gentype.FakeClientWithList[*v1alpha1.IsovalentCoreVRF, *v1alpha1.IsovalentCoreVRFList]
	Fake *FakeIsovalentV1alpha1
}

func newFakeIsovalentCoreVRFs(fake *FakeIsovalentV1alpha1) isovalentcomv1alpha1.IsovalentCoreVRFInterface {
	return &fakeIsovalentCoreVRFs{
		gentype.NewFakeClientWithList[*v1alpha1.IsovalentCoreVRF, *v1alpha1.IsovalentCoreVRFList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("isovalentcorevrfs"),
			v1alpha1.SchemeGroupVersion.WithKind("IsovalentCoreVRF"),
			func() *v1alpha1.IsovalentCoreVRF { return &v1alpha1.IsovalentCoreVRF{} },
			func() *v1alpha1.IsovalentCoreVRFList { return &v1alpha1.IsovalentCoreVRFList{} },
			func(dst, src *v1alpha1.IsovalentCoreVRFList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IsovalentCoreVRFList) []*v1alpha1.IsovalentCoreVRF {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IsovalentCoreVRFList, items []*v1alpha1.IsovalentCoreVRF) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
