// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIsovalentInspectionConfigs implements IsovalentInspectionConfigInterface
type fakeIsovalentInspectionConfigs struct {
	*gentype.FakeClientWithList[*v1alpha1.IsovalentInspectionConfig, *v1alpha1.IsovalentInspectionConfigList]
	Fake *FakeIsovalentV1alpha1
}

func newFakeIsovalentInspectionConfigs(fake *FakeIsovalentV1alpha1) isovalentcomv1alpha1.IsovalentInspectionConfigInterface {
	return &fakeIsovalentInspectionConfigs{
		gentype.NewFakeClientWithList[*v1alpha1.IsovalentInspectionConfig, *v1alpha1.IsovalentInspectionConfigList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("isovalentinspectionconfigs"),
			v1alpha1.SchemeGroupVersion.WithKind("IsovalentInspectionConfig"),
			func() *v1alpha1.IsovalentInspectionConfig { return &v1alpha1.IsovalentInspectionConfig{} },
			func() *v1alpha1.IsovalentInspectionConfigList { return &v1alpha1.IsovalentInspectionConfigList{} },
			func(dst, src *v1alpha1.IsovalentInspectionConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IsovalentInspectionConfigList) []*v1alpha1.IsovalentInspectionConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IsovalentInspectionConfigList, items []*v1alpha1.IsovalentInspectionConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
