// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIsovalentCoreVRFNodeStatuses implements IsovalentCoreVRFNodeStatusInterface
type fakeIsovalentCoreVRFNodeStatuses struct {
	*gentype.FakeClientWithList[*v1alpha1.IsovalentCoreVRFNodeStatus, *v1alpha1.IsovalentCoreVRFNodeStatusList]
	Fake *FakeIsovalentV1alpha1
}

func newFakeIsovalentCoreVRFNodeStatuses(fake *FakeIsovalentV1alpha1) isovalentcomv1alpha1.IsovalentCoreVRFNodeStatusInterface {
	return &fakeIsovalentCoreVRFNodeStatuses{
		gentype.NewFakeClientWithList[*v1alpha1.IsovalentCoreVRFNodeStatus, *v1alpha1.IsovalentCoreVRFNodeStatusList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("isovalentcorevrfnodestatuses"),
			v1alpha1.SchemeGroupVersion.WithKind("IsovalentCoreVRFNodeStatus"),
			func() *v1alpha1.IsovalentCoreVRFNodeStatus { return &v1alpha1.IsovalentCoreVRFNodeStatus{} },
			func() *v1alpha1.IsovalentCoreVRFNodeStatusList { return &v1alpha1.IsovalentCoreVRFNodeStatusList{} },
			func(dst, src *v1alpha1.IsovalentCoreVRFNodeStatusList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IsovalentCoreVRFNodeStatusList) []*v1alpha1.IsovalentCoreVRFNodeStatus {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IsovalentCoreVRFNodeStatusList, items []*v1alpha1.IsovalentCoreVRFNodeStatus) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
