//  Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
//  NOTICE: All information contained herein is, and remains the property of
//  Isovalent Inc and its suppliers, if any. The intellectual and technical
//  concepts contained herein are proprietary to Isovalent Inc and its suppliers
//  and may be covered by U.S. and Foreign Patents, patents in process, and are
//  protected by trade secret or copyright law.  Dissemination of this information
//  or reproduction of this material is strictly forbidden unless prior written
//  permission is obtained from Isovalent Inc.

package hooks

import (
	"context"
	_ "embed"
	"fmt"
	"maps"
	"strings"

	"github.com/spf13/pflag"
	v1 "k8s.io/api/core/v1"

	"github.com/cilium/cilium/cilium-cli/connectivity/builder/manifests/template"
	"github.com/cilium/cilium/cilium-cli/connectivity/check"
	"github.com/cilium/cilium/cilium-cli/enterprise/hooks/cli"
	enterpriseCheck "github.com/cilium/cilium/cilium-cli/enterprise/hooks/connectivity/check"
	"github.com/cilium/cilium/cilium-cli/enterprise/hooks/connectivity/deploy"
	enterpriseTests "github.com/cilium/cilium/cilium-cli/enterprise/hooks/connectivity/tests"
	enterpriseFeatures "github.com/cilium/cilium/cilium-cli/enterprise/hooks/utils/features"
	"github.com/cilium/cilium/cilium-cli/utils/features"
	k8sConst "github.com/cilium/cilium/pkg/k8s/apis/cilium.io"
	slimv1 "github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/meta/v1"
	"github.com/cilium/cilium/pkg/policy/api"
	"github.com/cilium/cilium/pkg/versioncheck"
)

const (
	testNoPolicies = "no-policies"
)

//go:embed manifests/client-egress-only-dns.yaml
var clientEgressOnlyDNSPolicyYAML string

//go:embed manifests/client-egress-dns-to-echo.yaml
var clientEgressDNSToEchoYAML string

//go:embed manifests/encrypt-client-to-echo-8080.yaml
var encryptClientToEchoYAML string

//go:embed manifests/unencrypt-client2-to-echo.yaml
var unencryptClient2ToEchoYAML string

type EnterpriseConnectivity struct {
	externalCiliumDNSProxyPods map[string]check.Pod
	mixedRoutingScenario       check.Scenario
}

func (ec *EnterpriseConnectivity) addConnectivityTests(cts ...*check.ConnectivityTest) error {
	templates, err := renderTemplates(cts[0])
	if err != nil {
		return fmt.Errorf("cannot render templates: %w", err)
	}

	if err := ec.addHubbleVersionTests(cts...); err != nil {
		return err
	}

	if err := ec.addExternalCiliumDNSProxyTests(cts[0], templates); err != nil {
		return err
	}

	if err := ec.addPhantomServiceTests(cts...); err != nil {
		return err
	}

	if cts[0].Params().IncludeUnsafeTests {
		if err := ec.addEgressGatewayHATests(cts[0], templates); err != nil {
			return err
		}
	}

	if enterpriseTests.Params.ConnDisrupt.IncludeConnDisruptTestEGWHA {
		if err := ec.addEgressGatewayHAConnDisruptTest(cts[0]); err != nil {
			return err
		}
	}

	if err := ec.addMulticastTests(cts[0]); err != nil {
		return err
	}

	if err := ec.addBGPTests(cts...); err != nil {
		return err
	}

	if err := ec.addBFDTests(cts[0]); err != nil {
		return err
	}

	if err := ec.addIngressPolicyTests(cts[0], templates); err != nil {
		return err
	}

	if err := ec.addEncryptionPolicyTests(cts...); err != nil {
		return err
	}

	if err := ec.addOrderedPolicyTests(cts[0], templates); err != nil {
		return err
	}

	if err := ec.addPassiveInspectionTests(cts[0]); err != nil {
		return err
	}

	// Always keep the mixed routing mode tests second to last, as they assert that the
	// correct routing mode was used to forward the packets generated by all
	// the other tests.
	if err := ec.addMixedRoutingTests(cts...); err != nil {
		return err
	}

	// As the very final test check if there were any failed diagnostics.
	// KEEP LAST!
	if err := ec.addDiagnosticsTest(cts[0]); err != nil {
		return err
	}

	return nil
}

func (ec *EnterpriseConnectivity) addConnectivityTestFlags(flags *pflag.FlagSet) {
	ec.addEgressGatewayHAFlags(flags)
}

func (ec *EnterpriseConnectivity) addHubbleVersionTests(cts ...*check.ConnectivityTest) error {
	mustGetTest(testNoPolicies, cts...).WithScenarios(enterpriseTests.HubbleCLIVersion())
	return nil
}

func (ec *EnterpriseConnectivity) addExternalCiliumDNSProxyTests(ct *check.ConnectivityTest, templates map[string]string) error {
	test := check.NewTest("cilium-dns-proxy-ha", ct.Params().Verbose, ct.Params().Debug)
	ct.AddTest(test).
		WithCiliumPolicy(templates["clientEgressOnlyDNSPolicyYAML"]).
		WithCiliumPolicy(clientEgressDNSToEchoYAML).
		WithFeatureRequirements(features.RequireEnabled(enterpriseFeatures.CiliumDNSProxyHA)).
		WithScenarios(enterpriseTests.ExternalCiliumDNSProxy(ec.externalCiliumDNSProxyPods)).
		WithExpectations(func(a *check.Action) (egress, ingress check.Result) {
			return check.ResultOK.ExpectMetricsIncrease(
					enterpriseTests.ExternalCiliumDNSProxySource(ec.externalCiliumDNSProxyPods),
					"isovalent_external_dns_proxy_policy_l7_total",
				),
				check.ResultNone
		})
	return nil
}

func (ec *EnterpriseConnectivity) addPhantomServiceTests(cts ...*check.ConnectivityTest) (err error) {
	if cts[0].Params().MultiCluster == "" {
		return nil
	}

	if ok, _ := cts[0].Features.MatchRequirements(features.RequireEnabled(enterpriseFeatures.PhantomServices)); !ok {
		return nil
	}

	defer func() {
		if r := recover(); r != nil {
			err = r.(error)
		}
	}()

	mustGetTest("no-policies", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())
	mustGetTest("allow-all-except-world", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())

	// Traffic shall be dropped, because it is subject to the ingress/egress policy.
	mustGetTest("all-ingress-deny", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())
	mustGetTest("all-ingress-deny-knp", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())
	mustGetTest("all-egress-deny", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())
	mustGetTest("all-egress-deny-knp", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())
	mustGetTest("cluster-entity-multi-cluster", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())

	// Traffic shall be allowed, because it matches the cross-cluster policy.
	mustGetTest("client-egress", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())
	mustGetTest("client-egress-knp", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())

	return
}

func (ec *EnterpriseConnectivity) addEncryptionPolicyTests(cts ...*check.ConnectivityTest) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = r.(error)
		}
	}()

	// Regular encryption related tests cannot be run (neither in sanity nor assert mode) if
	// encryption policies are enabled, as not all traffic in the cluster will be encrypted.
	mustGetTest("pod-to-pod-encryption", cts...).WithFeatureRequirements(
		features.RequireDisabled(enterpriseFeatures.EncryptionPolicy),
		features.RequireDisabled(enterpriseFeatures.RemoteEncryptionPolicy),
	)
	mustGetTest("pod-to-pod-with-l7-policy-encryption", cts...).WithFeatureRequirements(
		features.RequireDisabled(enterpriseFeatures.EncryptionPolicy),
		features.RequireDisabled(enterpriseFeatures.RemoteEncryptionPolicy),
	)
	mustGetTest("node-to-node-encryption", cts...).WithFeatureRequirements(
		features.RequireDisabled(enterpriseFeatures.EncryptionPolicy),
		features.RequireDisabled(enterpriseFeatures.RemoteEncryptionPolicy),
	)
	mustGetTest("pod-to-pod-encryption-v2", cts...).WithFeatureRequirements(
		features.RequireDisabled(enterpriseFeatures.EncryptionPolicy),
		features.RequireDisabled(enterpriseFeatures.RemoteEncryptionPolicy),
	)
	mustGetTest("pod-to-pod-with-l7-policy-encryption-v2", cts...).WithFeatureRequirements(
		features.RequireDisabled(enterpriseFeatures.EncryptionPolicy),
		features.RequireDisabled(enterpriseFeatures.RemoteEncryptionPolicy),
	)

	newTest := func(ct *check.ConnectivityTest, name string) *enterpriseCheck.EnterpriseTest {
		return enterpriseCheck.NewEnterpriseConnectivityTest(ct).
			NewEnterpriseTest(name).
			WithFeatureRequirements(features.RequireEnabled(enterpriseFeatures.EncryptionPolicy)).
			WithCondition(func() bool {
				if ct.Params().MultiCluster != "" {
					if ok, _ := ct.Features.MatchRequirements(features.RequireEnabled(enterpriseFeatures.RemoteEncryptionPolicy)); !ok {
						return false
					}
				}
				return true
			}).
			WithCondition(func() bool { return !ct.Params().SingleNode })
	}

	if versioncheck.MustCompile(">=1.16.0")(cts[0].CiliumVersion) {
		newTest(cts[0], "pod-to-pod-encryption-policy").
			WithFeatureRequirements(features.RequireDisabled(enterpriseFeatures.EncryptionPolicyFallbackEncrypt)).
			WithIsovalentClusterwideEncryptionPolicy(encryptClientToEchoYAML).
			WithScenarios(enterpriseTests.PodToPodEncryptionPolicy())
	}

	if versioncheck.MustCompile(">=1.19.0")(cts[0].CiliumVersion) {
		newTest(cts[0], "pod-to-pod-encryption-policy-optout").
			WithFeatureRequirements(features.RequireEnabled(enterpriseFeatures.EncryptionPolicyFallbackEncrypt)).
			WithIsovalentClusterwideEncryptionPolicy(unencryptClient2ToEchoYAML).
			WithScenarios(enterpriseTests.PodToPodEncryptionPolicyOptOut())
	}

	return nil
}

func (ec *EnterpriseConnectivity) addMixedRoutingTests(cts ...*check.ConnectivityTest) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = r.(error)
		}
	}()

	// Encryption related tests cannot be run (neither in sanity nor assert mode) if
	// the two clusters are configured with different routing modes, because the
	// tcpdump filters to assert no unencrypted packet is leaked would be incorrect.
	mustGetTest("pod-to-pod-encryption", cts...).WithFeatureRequirements(features.RequireDisabled(enterpriseFeatures.MixedRoutingMode))
	mustGetTest("node-to-node-encryption", cts...).WithFeatureRequirements(features.RequireDisabled(enterpriseFeatures.MixedRoutingMode))
	mustGetTest("pod-to-pod-encryption-v2", cts...).WithFeatureRequirements(features.RequireDisabled(enterpriseFeatures.MixedRoutingMode))
	mustGetTest("pod-to-pod-with-l7-policy-encryption-v2", cts...).WithFeatureRequirements(features.RequireDisabled(enterpriseFeatures.MixedRoutingMode))

	// Requirements changes should be additionally applied to the ones guarding
	// the execution of the associated setup function, so that they always match.
	if cts[0].Params().IncludeUnsafeTests {
		// Generate extra traffic from one pod in each cluster to each Cilium
		// HealthIP, to prevent the sanity checks from reporting false positives
		// due to the lack of other traffic flowing in the cluster. The already
		// existing health check test is not sufficient when WireGuard is enabled,
		// because node to pod traffic is not encrypted by default.
		cts[0].AddTest(check.NewTest("mixed-routing-extra-traffic", cts[0].Params().Verbose, cts[0].Params().Debug)).
			WithFeatureRequirements(
				features.RequireEnabled(features.HealthChecking),
				features.RequireEnabled(enterpriseFeatures.FallbackRoutingMode),
			).
			WithScenarios(enterpriseTests.MixedRoutingExtraTraffic())

		cts[0].AddTest(check.NewTest("mixed-routing", cts[0].Params().Verbose, cts[0].Params().Debug)).
			WithFeatureRequirements(features.RequireEnabled(enterpriseFeatures.FallbackRoutingMode)).
			WithSysdumpPolicy(check.SysdumpPolicyNever).
			WithScenarios(ec.mixedRoutingScenario)
	}

	return nil
}

func (ec *EnterpriseConnectivity) addMulticastTests(ct *check.ConnectivityTest) (err error) {
	newTest := func(ct *check.ConnectivityTest, name string) *enterpriseCheck.EnterpriseTest {
		return enterpriseCheck.NewEnterpriseConnectivityTest(ct).
			NewEnterpriseTest(name).
			WithFeatureRequirements(
				features.RequireEnabled(enterpriseFeatures.Multicast),
			)
	}

	// test igmp v2
	igmpv2Test := newTest(ct, "multicast-igmpv2-check").
		WithMulticastDeployment(enterpriseCheck.MulticastDeploymentParams{
			Name: "multicast-source-v2",
			Labels: map[string]string{
				enterpriseTests.MulticastLabelKey: enterpriseTests.SourceLabel,
			},
		}).
		WithMulticastDeployment(enterpriseCheck.MulticastDeploymentParams{
			Name: "multicast-subscriber-v2",
			Labels: map[string]string{
				enterpriseTests.MulticastLabelKey: enterpriseTests.SubscriberLabel,
			},
			IGMPVersion: 2,
		}).
		WithIsovalentMulticastGroup(
			enterpriseCheck.IsovalentMulticastGroupParams{
				Name:            "igmpv2-version-test",
				GroupAddrPrefix: "226.1.0.0",
				Groups:          5,
			})
	igmpv2Test.WithScenarios(enterpriseTests.MulticastGroupCheck(igmpv2Test.Context().EntClients()))

	// test igmp v3 group check
	igmpv3Test := newTest(ct, "multicast-igmpv3-check").
		WithMulticastDeployment(enterpriseCheck.MulticastDeploymentParams{
			Name: "multicast-source-v3",
			Labels: map[string]string{
				enterpriseTests.MulticastLabelKey: enterpriseTests.SourceLabel,
			},
		}).
		WithMulticastDeployment(enterpriseCheck.MulticastDeploymentParams{
			Name: "multicast-subscriber-v3",
			Labels: map[string]string{
				enterpriseTests.MulticastLabelKey: enterpriseTests.SubscriberLabel,
			},
			IGMPVersion: 3,
		}).
		WithIsovalentMulticastGroup(
			enterpriseCheck.IsovalentMulticastGroupParams{
				Name:            "igmpv3-version-test",
				GroupAddrPrefix: "226.2.0.0",
				Groups:          5,
			})
	igmpv3Test.WithScenarios(enterpriseTests.MulticastGroupCheck(igmpv3Test.Context().EntClients()))

	// check multicast connectivity
	mcastConnectivityTest := newTest(ct, "multicast-connectivity").
		WithMulticastDeployment(enterpriseCheck.MulticastDeploymentParams{
			Name: "multicast-source-conn",
			Labels: map[string]string{
				enterpriseTests.MulticastLabelKey: enterpriseTests.SourceLabel,
			},
		}).
		WithMulticastDeployment(enterpriseCheck.MulticastDeploymentParams{
			Name: "multicast-subscriber-conn",
			Labels: map[string]string{
				enterpriseTests.MulticastLabelKey: enterpriseTests.SubscriberLabel,
			},
			IGMPVersion: 3,
		}).
		WithIsovalentMulticastGroup(
			enterpriseCheck.IsovalentMulticastGroupParams{
				Name:            "conn-test",
				GroupAddrPrefix: "226.4.0.0",
				Groups:          5,
			})
	mcastConnectivityTest.WithScenarios(enterpriseTests.MulticastConnectivity(mcastConnectivityTest.Context().EntClients(), 100))

	return nil
}

func (ec *EnterpriseConnectivity) addBGPTests(cts ...*check.ConnectivityTest) (err error) {
	// disable OSS BGP tests if enterprise BGP CP is enabled
	// (OSS BGP CP can not be used at the same time as CEE)
	for _, ct := range cts { // look into all concurrent groups
		if ossv2Test, err := ct.GetTest("bgp-control-plane-v2"); err == nil {
			ossv2Test.WithFeatureRequirements(
				features.RequireDisabled(enterpriseFeatures.EnterpriseBGPControlPlane),
			)
		}
	}

	newTest := func(ct *check.ConnectivityTest, name string) *enterpriseCheck.EnterpriseTest {
		return enterpriseCheck.NewEnterpriseConnectivityTest(ct).
			NewEnterpriseTest(name).
			WithFeatureRequirements(
				features.RequireEnabled(enterpriseFeatures.EnterpriseBGPControlPlane),
				features.RequireEnabled(features.BGPControlPlane),
				features.RequireEnabled(features.NodeWithoutCilium),
			)
	}

	// add CEE BGP CP test to group 0 as the remaining CEE tests, for now it always needs to be in the same group
	// as BFD tests as they are using BGP as well and cannot run concurrently
	newTest(cts[0], "seq-enterprise-bgp-control-plane-v2").
		WithScenarios(enterpriseTests.BGPSvcAdvertisements())

	return nil
}

func (ec *EnterpriseConnectivity) addBFDTests(ct *check.ConnectivityTest) (err error) {
	bfdStandaloneTest := func(ct *check.ConnectivityTest) *enterpriseCheck.EnterpriseTest {
		return enterpriseCheck.NewEnterpriseConnectivityTest(ct).
			NewEnterpriseTest("seq-bfd-standalone"). // prefix the test name with `seq-` to run it sequentially
			WithFeatureRequirements(
				features.RequireEnabled(enterpriseFeatures.BFD),
				features.RequireEnabled(features.NodeWithoutCilium),
			)
	}
	bfdStandaloneTest(ct).WithScenarios(
		enterpriseTests.BFDStandAlone(enterpriseTests.BFDStandAloneParams{
			MultiHop:     false,
			EchoFunction: false,
		}),
		enterpriseTests.BFDStandAlone(enterpriseTests.BFDStandAloneParams{
			MultiHop:     false,
			EchoFunction: true,
		}),
		enterpriseTests.BFDStandAlone(enterpriseTests.BFDStandAloneParams{
			MultiHop:     true,
			EchoFunction: false,
		}),
	)

	bfdBGPTest := func(ct *check.ConnectivityTest) *enterpriseCheck.EnterpriseTest {
		return enterpriseCheck.NewEnterpriseConnectivityTest(ct).
			NewEnterpriseTest("seq-bfd-bgp"). // prefix the test name with `seq-` to run it sequentially
			WithFeatureRequirements(
				features.RequireEnabled(enterpriseFeatures.BFD),
				features.RequireEnabled(features.NodeWithoutCilium),
				features.RequireEnabled(enterpriseFeatures.EnterpriseBGPControlPlane),
				features.RequireEnabled(features.BGPControlPlane),
			)
	}
	bfdBGPTest(ct).WithScenarios(enterpriseTests.BFDWithBGP())

	return nil
}

func (ec *EnterpriseConnectivity) addDiagnosticsTest(ct *check.ConnectivityTest) (err error) {
	enterpriseCheck.NewEnterpriseConnectivityTest(ct).
		NewEnterpriseTest("seq-diagnostics").
		WithScenarios(diagnosticsScenario{ScenarioBase: check.NewScenarioBase()})

	return nil
}

type diagnosticsScenario struct {
	check.ScenarioBase
}

// Name implements check.Scenario.
func (d diagnosticsScenario) Name() string {
	return "diagnostics"
}

// Run implements check.Scenario.
func (d diagnosticsScenario) Run(ctx context.Context, t *check.Test) {
	ct := t.Context()

	t.NewGenericAction(d, "diagnostics").Run(func(a *check.Action) {
		var buf strings.Builder
		fail, err := cli.CollectAndPrintDiagnostics(
			ctx,
			func(yield func(*v1.Pod) bool) {
				for _, pod := range ct.CiliumPods() {
					if !yield(pod.Pod) {
						break
					}
				}
			},
			ct.K8sClient(),
			false,
			&buf,
		)
		if err != nil {
			a.Failf("Error: %s", err)
		} else if fail {
			a.Fail(buf.String())
		}
	})
}

var _ check.Scenario = diagnosticsScenario{}

func inspectionWorkloadName(scope, suffix string) string {
	return fmt.Sprintf("%s-%s", scope, suffix)
}

func inspectionWorkloadLabels(scope string, extra map[string]string) map[string]string {
	labels := enterpriseTests.InspectionScopeLabels(scope)
	if labels == nil {
		labels = map[string]string{}
	}
	maps.Copy(labels, extra)
	return labels
}

func (ec *EnterpriseConnectivity) addPassiveInspectionTests(ct *check.ConnectivityTest) error {
	entCT := enterpriseCheck.NewEnterpriseConnectivityTest(ct)
	includedScenarioExcludedNamespace := fmt.Sprintf("%s-inspection-included-skip-%d", ct.Params().TestNamespace, ct.Params().TestNamespaceIndex)
	excludedScenarioNamespace := fmt.Sprintf("%s-inspection-excluded-%d", ct.Params().TestNamespace, ct.Params().TestNamespaceIndex)
	passiveInspectionScope := "passive-inspection-phased"
	includedNamespaceScope := "passive-inspection-included-namespace"
	selectedPodsScope := "passive-inspection-selected-pods"
	excludedNamespaceScope := "passive-inspection-excluded-namespace"
	passiveInspectionSelectors := enterpriseTests.InspectionSelectorsForScope(passiveInspectionScope)
	includedNamespaceSelectors := enterpriseTests.InspectionSelectorsForScope(includedNamespaceScope)
	excludedNamespaceSelectors := enterpriseTests.InspectionSelectorsForScope(excludedNamespaceScope)
	selectedPodSelector := enterpriseTests.InspectionScopedSelector(selectedPodsScope,
		fmt.Sprintf("%s=%s", enterpriseTests.InspectionSelectionLabelKey, enterpriseTests.InspectionSelectionSelected))
	skippedPodSelector := enterpriseTests.InspectionScopedSelector(selectedPodsScope,
		fmt.Sprintf("%s=%s", enterpriseTests.InspectionSelectionLabelKey, enterpriseTests.InspectionSelectionSkipped))

	entCT.NewEnterpriseTest("passive-inspection").
		WithFeatureRequirements(
			features.RequireEnabled(enterpriseFeatures.PassiveInspection),
		).
		WithInspectionSnifferDaemonSet(enterpriseCheck.InspectionSnifferDaemonSetParams{
			Name:   inspectionWorkloadName(passiveInspectionScope, "sniffer"),
			Labels: enterpriseTests.InspectionScopeLabels(passiveInspectionScope),
		}).
		WithInspectionSenderDeployment(enterpriseCheck.InspectionSenderDeploymentParams{
			Name:   inspectionWorkloadName(passiveInspectionScope, "sender"),
			Labels: enterpriseTests.InspectionScopeLabels(passiveInspectionScope),
		}).
		WithInspectionSenderDeployment(enterpriseCheck.InspectionSenderDeploymentParams{
			Name:   inspectionWorkloadName(includedNamespaceScope, "sender"),
			Labels: enterpriseTests.InspectionScopeLabels(includedNamespaceScope),
		}).
		WithInspectionSenderDeployment(enterpriseCheck.InspectionSenderDeploymentParams{
			Name:      inspectionWorkloadName(includedNamespaceScope, "sender"),
			Namespace: includedScenarioExcludedNamespace,
			Labels:    enterpriseTests.InspectionScopeLabels(includedNamespaceScope),
		}).
		WithInspectionSenderDeployment(enterpriseCheck.InspectionSenderDeploymentParams{
			Name: inspectionWorkloadName(selectedPodsScope, "sender-selected"),
			Labels: inspectionWorkloadLabels(selectedPodsScope, map[string]string{
				enterpriseTests.InspectionSelectionLabelKey: enterpriseTests.InspectionSelectionSelected,
			}),
		}).
		WithInspectionSenderDeployment(enterpriseCheck.InspectionSenderDeploymentParams{
			Name: inspectionWorkloadName(selectedPodsScope, "sender-skipped"),
			Labels: inspectionWorkloadLabels(selectedPodsScope, map[string]string{
				enterpriseTests.InspectionSelectionLabelKey: enterpriseTests.InspectionSelectionSkipped,
			}),
		}).
		WithInspectionSenderDeployment(enterpriseCheck.InspectionSenderDeploymentParams{
			Name:   inspectionWorkloadName(excludedNamespaceScope, "sender"),
			Labels: enterpriseTests.InspectionScopeLabels(excludedNamespaceScope),
		}).
		WithInspectionSenderDeployment(enterpriseCheck.InspectionSenderDeploymentParams{
			Name:      inspectionWorkloadName(excludedNamespaceScope, "sender"),
			Namespace: excludedScenarioNamespace,
			Labels:    enterpriseTests.InspectionScopeLabels(excludedNamespaceScope),
		}).
		WithScenarios(enterpriseTests.PassiveInspectionPhasedVerification(
			enterpriseTests.PassiveInspectionPhase{
				Name:                   "default",
				DeleteInspectionConfig: true,
				SnifferSelector:        passiveInspectionSelectors.SnifferSelector,
				IncludedSelector:       passiveInspectionSelectors.SenderSelector,
				IncludedTagPrefix:      "inspection-default-",
			},
			enterpriseTests.PassiveInspectionPhase{
				Name: "included-namespace",
				EndpointSelector: &api.EndpointSelector{LabelSelector: &slimv1.LabelSelector{
					MatchLabels: map[string]string{
						k8sConst.PodNamespaceLabel:              ct.Params().TestNamespace,
						enterpriseTests.InspectionScopeLabelKey: includedNamespaceScope,
					},
				}},
				SnifferSelector:   passiveInspectionSelectors.SnifferSelector,
				IncludedSelector:  includedNamespaceSelectors.SenderSelector,
				IncludedTagPrefix: "inspection-namespace-include-",
				ExcludedNamespace: includedScenarioExcludedNamespace,
				ExcludedSelector:  includedNamespaceSelectors.SenderSelector,
				ExcludedTagPrefix: "inspection-namespace-exclude-",
			},
			enterpriseTests.PassiveInspectionPhase{
				Name: "selected-pods",
				EndpointSelector: &api.EndpointSelector{LabelSelector: &slimv1.LabelSelector{
					MatchLabels: map[string]string{
						enterpriseTests.InspectionScopeLabelKey:     selectedPodsScope,
						enterpriseTests.InspectionSelectionLabelKey: enterpriseTests.InspectionSelectionSelected,
					},
				}},
				SnifferSelector:   passiveInspectionSelectors.SnifferSelector,
				IncludedSelector:  selectedPodSelector,
				IncludedTagPrefix: "inspection-pod-include-",
				ExcludedSelector:  skippedPodSelector,
				ExcludedTagPrefix: "inspection-pod-exclude-",
			},
			enterpriseTests.PassiveInspectionPhase{
				Name: "excluded-namespace",
				EndpointSelector: &api.EndpointSelector{LabelSelector: &slimv1.LabelSelector{
					MatchLabels: map[string]string{
						enterpriseTests.InspectionScopeLabelKey: excludedNamespaceScope,
					},
					MatchExpressions: []slimv1.LabelSelectorRequirement{{
						Key:      k8sConst.PodNamespaceLabel,
						Operator: slimv1.LabelSelectorOpNotIn,
						Values:   []string{excludedScenarioNamespace},
					}},
				}},
				SnifferSelector:   passiveInspectionSelectors.SnifferSelector,
				IncludedSelector:  excludedNamespaceSelectors.SenderSelector,
				IncludedTagPrefix: "inspection-notin-include-",
				ExcludedNamespace: excludedScenarioNamespace,
				ExcludedSelector:  excludedNamespaceSelectors.SenderSelector,
				ExcludedTagPrefix: "inspection-notin-exclude-",
			},
		))

	return nil
}

func mustGetTest(testName string, cts ...*check.ConnectivityTest) *check.Test {
	var (
		test *check.Test
		err  error
	)
	for i := range cts {
		if test, err = cts[i].GetTest(testName); err == nil {
			return test
		}
	}
	panic(fmt.Errorf("failed to get test %s: %w", testName, err))
}

func renderTemplates(ct *check.ConnectivityTest) (map[string]string, error) {
	templates := map[string]string{
		"clientEgressL7HTTPAnywhereYAML":        clientEgressL7HTTPAnywhereYAML,
		"clientEgressOnlyDNSPolicyYAML":         clientEgressOnlyDNSPolicyYAML,
		"clientIngressToEchoOrderedNS":          clientIngressToEchoOrderedNS,
		"clientIngressToEchoOrderedWildcard":    clientIngressToEchoOrderedWildcard,
		"clientIngressToEchoOrderedPortrange":   clientIngressToEchoOrderedPortrange,
		"clientIngressToEchoTieredNS":           clientIngressToEchoTieredNS,
		"clientIngressToEchoTieredWildcard":     clientIngressToEchoTieredWildcard,
		"clientIngressToEchoTieredWildcardPass": clientIngressToEchoTieredWildcardPass,
	}

	renderedTemplates := map[string]string{}
	for key, temp := range templates {
		val, err := template.Render(temp, struct {
			check.Parameters
			ClusterNameLocal  string
			ClusterNameRemote string
		}{
			Parameters:        ct.Params(),
			ClusterNameLocal:  ct.ClusterNameLocal,
			ClusterNameRemote: ct.ClusterNameRemote,
		})
		if err != nil {
			return nil, err
		}
		renderedTemplates[key] = val
	}
	return renderedTemplates, nil
}
