# Copyright Authors of Cilium
# SPDX-License-Identifier: Apache-2.0

# This Makefile is expected to run inside the cilium-builder image to generate
# the Go files from the protocol buffer definitions.

PROTO_FILES := ./v1/service_health.proto

PROTOC := protoc
PROTOC_FLAGS := -I. -I/src/tools/protobuf
PROTOC_PLUGINS := --plugin=$(GOPATH)/bin/protoc-gen-go
PROTOC_PLUGINS += --plugin=$(GOPATH)/bin/protoc-gen-go-grpc
GO_OUT := --go_out=. --go_opt=paths=source_relative
GO_GRPC_OUT := --go-grpc_out=. --go-grpc_opt=paths=source_relative

.PHONY: all
all: proto

.PHONY: proto
proto:
	$(PROTOC) $(PROTOC_FLAGS) $(PROTOC_PLUGINS) $(GO_OUT) $(GO_GRPC_OUT) $(PROTO_FILES)
