// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IsovalentCoreVRFsGetter has a method to return a IsovalentCoreVRFInterface.
// A group's client should implement this interface.
type IsovalentCoreVRFsGetter interface {
	IsovalentCoreVRFs() IsovalentCoreVRFInterface
}

// IsovalentCoreVRFInterface has methods to work with IsovalentCoreVRF resources.
type IsovalentCoreVRFInterface interface {
	Create(ctx context.Context, isovalentCoreVRF *isovalentcomv1alpha1.IsovalentCoreVRF, opts v1.CreateOptions) (*isovalentcomv1alpha1.IsovalentCoreVRF, error)
	Update(ctx context.Context, isovalentCoreVRF *isovalentcomv1alpha1.IsovalentCoreVRF, opts v1.UpdateOptions) (*isovalentcomv1alpha1.IsovalentCoreVRF, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*isovalentcomv1alpha1.IsovalentCoreVRF, error)
	List(ctx context.Context, opts v1.ListOptions) (*isovalentcomv1alpha1.IsovalentCoreVRFList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *isovalentcomv1alpha1.IsovalentCoreVRF, err error)
	IsovalentCoreVRFExpansion
}

// isovalentCoreVRFs implements IsovalentCoreVRFInterface
type isovalentCoreVRFs struct {
	*gentype.ClientWithList[*isovalentcomv1alpha1.IsovalentCoreVRF, *isovalentcomv1alpha1.IsovalentCoreVRFList]
}

// newIsovalentCoreVRFs returns a IsovalentCoreVRFs
func newIsovalentCoreVRFs(c *IsovalentV1alpha1Client) *isovalentCoreVRFs {
	return &isovalentCoreVRFs{
		gentype.NewClientWithList[*isovalentcomv1alpha1.IsovalentCoreVRF, *isovalentcomv1alpha1.IsovalentCoreVRFList](
			"isovalentcorevrfs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *isovalentcomv1alpha1.IsovalentCoreVRF { return &isovalentcomv1alpha1.IsovalentCoreVRF{} },
			func() *isovalentcomv1alpha1.IsovalentCoreVRFList { return &isovalentcomv1alpha1.IsovalentCoreVRFList{} },
		),
	}
}
