// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IsovalentCoreVRFNodeStatusesGetter has a method to return a IsovalentCoreVRFNodeStatusInterface.
// A group's client should implement this interface.
type IsovalentCoreVRFNodeStatusesGetter interface {
	IsovalentCoreVRFNodeStatuses() IsovalentCoreVRFNodeStatusInterface
}

// IsovalentCoreVRFNodeStatusInterface has methods to work with IsovalentCoreVRFNodeStatus resources.
type IsovalentCoreVRFNodeStatusInterface interface {
	Create(ctx context.Context, isovalentCoreVRFNodeStatus *isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus, opts v1.CreateOptions) (*isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus, error)
	Update(ctx context.Context, isovalentCoreVRFNodeStatus *isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus, opts v1.UpdateOptions) (*isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, isovalentCoreVRFNodeStatus *isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus, opts v1.UpdateOptions) (*isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus, error)
	List(ctx context.Context, opts v1.ListOptions) (*isovalentcomv1alpha1.IsovalentCoreVRFNodeStatusList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus, err error)
	IsovalentCoreVRFNodeStatusExpansion
}

// isovalentCoreVRFNodeStatuses implements IsovalentCoreVRFNodeStatusInterface
type isovalentCoreVRFNodeStatuses struct {
	*gentype.ClientWithList[*isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus, *isovalentcomv1alpha1.IsovalentCoreVRFNodeStatusList]
}

// newIsovalentCoreVRFNodeStatuses returns a IsovalentCoreVRFNodeStatuses
func newIsovalentCoreVRFNodeStatuses(c *IsovalentV1alpha1Client) *isovalentCoreVRFNodeStatuses {
	return &isovalentCoreVRFNodeStatuses{
		gentype.NewClientWithList[*isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus, *isovalentcomv1alpha1.IsovalentCoreVRFNodeStatusList](
			"isovalentcorevrfnodestatuses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus {
				return &isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus{}
			},
			func() *isovalentcomv1alpha1.IsovalentCoreVRFNodeStatusList {
				return &isovalentcomv1alpha1.IsovalentCoreVRFNodeStatusList{}
			},
		),
	}
}
