// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IsovalentInspectionConfigsGetter has a method to return a IsovalentInspectionConfigInterface.
// A group's client should implement this interface.
type IsovalentInspectionConfigsGetter interface {
	IsovalentInspectionConfigs() IsovalentInspectionConfigInterface
}

// IsovalentInspectionConfigInterface has methods to work with IsovalentInspectionConfig resources.
type IsovalentInspectionConfigInterface interface {
	Create(ctx context.Context, isovalentInspectionConfig *isovalentcomv1alpha1.IsovalentInspectionConfig, opts v1.CreateOptions) (*isovalentcomv1alpha1.IsovalentInspectionConfig, error)
	Update(ctx context.Context, isovalentInspectionConfig *isovalentcomv1alpha1.IsovalentInspectionConfig, opts v1.UpdateOptions) (*isovalentcomv1alpha1.IsovalentInspectionConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*isovalentcomv1alpha1.IsovalentInspectionConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*isovalentcomv1alpha1.IsovalentInspectionConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *isovalentcomv1alpha1.IsovalentInspectionConfig, err error)
	IsovalentInspectionConfigExpansion
}

// isovalentInspectionConfigs implements IsovalentInspectionConfigInterface
type isovalentInspectionConfigs struct {
	*gentype.ClientWithList[*isovalentcomv1alpha1.IsovalentInspectionConfig, *isovalentcomv1alpha1.IsovalentInspectionConfigList]
}

// newIsovalentInspectionConfigs returns a IsovalentInspectionConfigs
func newIsovalentInspectionConfigs(c *IsovalentV1alpha1Client) *isovalentInspectionConfigs {
	return &isovalentInspectionConfigs{
		gentype.NewClientWithList[*isovalentcomv1alpha1.IsovalentInspectionConfig, *isovalentcomv1alpha1.IsovalentInspectionConfigList](
			"isovalentinspectionconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *isovalentcomv1alpha1.IsovalentInspectionConfig {
				return &isovalentcomv1alpha1.IsovalentInspectionConfig{}
			},
			func() *isovalentcomv1alpha1.IsovalentInspectionConfigList {
				return &isovalentcomv1alpha1.IsovalentInspectionConfigList{}
			},
		),
	}
}
