{
 "title": "ClickHouse Tables",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(clickhouse_system_parts_rows,namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(clickhouse_system_parts_rows,service)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(clickhouse_system_parts_rows,database)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values(clickhouse_system_parts_rows,table)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Table size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (database, table) (clickhouse_system_parts_total_size{namespace=~\"$namespace\", service=~\"$service\", database=~\"$database\", table=~\"$table\"})",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Table row count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (database, table) (clickhouse_system_parts_rows{namespace=~\"$namespace\", service=~\"$service\", database=~\"$database\", table=~\"$table\"})",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Table largest part size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (database, table) (clickhouse_system_parts_largest_size{namespace=~\"$namespace\", service=~\"$service\", database=~\"$database\", table=~\"$table\"})",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Table parts count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (database, table, state) (clickhouse_system_parts_count{namespace=~\"$namespace\", service=~\"$service\", database=~\"$database\", table=~\"$table\"})",
     "legendFormat": "{{database}}.{{table}} - {{state}}"
    }
   ]
  },
  {
   "title": "Table primary keys size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (database, table) (clickhouse_system_parts_primary_keys_size{namespace=~\"$namespace\", service=~\"$service\", database=~\"$database\", table=~\"$table\"})",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  }
 ]
}