{
 "title": "Timescape Analyzer",
 "tags": [ "hubble-timescape" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(timescape_build_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(timescape_build_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Analyzer Enabled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(timescape_analyzer_running{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generated Reports",
   "type": "stat",
   "description": "The total number of reports generated.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(timescape_analyzer_report_generation_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__range]))\n-\n(\n    sum(increase(timescape_analyzer_report_generation_failed_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__range]))\n    +\n    sum(increase(timescape_analyzer_report_storage_failed_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__range]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Report Generation Failures",
   "type": "stat",
   "description": "The total number of reports generation that failed.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(timescape_analyzer_report_generation_failed_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Report Storage Failures",
   "type": "stat",
   "description": "The total number of reports store operation in the database that failed.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(timescape_analyzer_report_storage_failed_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": {
    "content": "The analyzer service is part of the **Network Security Assessment** system.\n\nIt generates assessment reports and inserts them in the database at regular\nintervals based on network identities and policies in the Kubernetes cluster.\n\nThe assessment reports can be visualized in Timescape UI.\n"
   }
  },
  {
   "title": "Job Durations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(timescape_analyzer_report_generation_duration_seconds_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))\n/\nsum(rate(timescape_analyzer_report_generation_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "generation"
    },
    {
     "expr": "sum(rate(timescape_analyzer_report_storage_duration_seconds_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))\n/\nsum(rate(timescape_analyzer_report_storage_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "storage"
    }
   ]
  }
 ]
}