{
 "title": "Timescape Ingestion",
 "tags": [ "hubble-timescape" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(timescape_build_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(timescape_build_info, namespace)"
    }
   },
   {
    "name": "event_types",
    "label": "Event Types",
    "query": {
     "query": "label_values(timescape_ingester_decoder_decoded_events_count{namespace=\"$namespace\"},event_type)"
    }
   },
   {
    "name": "event_types_not_unknown",
    "query": {
     "query": "label_values(timescape_ingester_decoder_decoded_events_count{namespace=\"$namespace\", event_type=~\"$event_types\", event_type!=\"unknown\"},event_type)"
    }
   },
   {
    "name": "ingestion_source",
    "label": "Ingestion Source",
    "query": {
     "query": "label_values(timescape_ingester_inserter_last_event_timestamp{namespace=\"$namespace\", event_type!=\"unknown\"},source)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Ingestion Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Is ingest running?",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "timescape_ingester_ingest_running{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Newest timestamp ingested",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (event_type) (max_over_time(timescape_ingester_inserter_last_event_timestamp{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__range])) * 1000 != 0",
     "legendFormat": "{{ event_type }}"
    }
   ]
  },
  {
   "title": "Total events ingested",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (event_type) (increase(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\",namespace=~\"$namespace\", event_type=~\"$event_types\",event_type!=\"unknown\"}[$__range]))",
     "legendFormat": "{{ event_type }}"
    }
   ]
  },
  {
   "title": "Avg ingestion throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (event_type) (rate(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\",namespace=~\"$namespace\",event_type=~\"$event_types\",event_type!=\"unknown\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current ingest rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by (event_type) (rate(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",event_type=~\"$event_types\",event_type!=\"unknown\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Staleness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(time() - (max by (event_type) (max_over_time(timescape_ingester_inserter_last_event_timestamp{cluster=~\"$cluster\", namespace=~\"$namespace\",event_type=~\"$event_types\",event_type!~\"unknown|k8s-events\"}[1h])) != 0))",
     "legendFormat": "{{ event_type }} staleness"
    }
   ]
  },
  {
   "title": "Ingest rate 1d avg vs 7d avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",event_type=~\"$event_types\",event_type!=\"unknown\"}[1d]))",
     "legendFormat": "1 day"
    },
    {
     "expr": "sum(rate(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", event_type=~\"$event_types\",event_type!=\"unknown\"}[1w]))",
     "legendFormat": "7 days"
    }
   ]
  },
  {
   "title": "Ingest rate this week vs last week",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by () (rate(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", event_type=~\"$event_types\",event_type!=\"unknown\"}[1w]))",
     "legendFormat": "this week"
    },
    {
     "expr": "sum by () (rate(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", event_type=~\"$event_types\",event_type!=\"unknown\"}[1w] offset 1w))",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Average per-stage durations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(timescape_ingester_lister_list_duration_seconds_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))\n/\nsum(rate(timescape_ingester_lister_list_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "avg list duration"
    },
    {
     "expr": "sum(rate(timescape_ingester_filter_batch_duration_seconds_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))\n/\nsum(rate(timescape_ingester_filter_batch_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "avg filter batch duration"
    },
    {
     "expr": "sum(rate(timescape_ingester_walker_task_duration_seconds_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))\n/\nsum(rate(timescape_ingester_walker_task_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "avg walk task duration"
    },
    {
     "expr": "sum(rate(timescape_ingester_inserter_event_batch_duration_seconds_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))\n/\nsum(rate(timescape_ingester_inserter_event_batch_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "avg insert batch duration"
    }
   ]
  },
  {
   "title": "Queue size per-stage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(timescape_coordinator_filter_queue_size{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Coordinator filter"
    },
    {
     "expr": "sum(rate(timescape_coordinator_unprocessed_queue_size{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Coordinator unprocessed"
    },
    {
     "expr": "sum(rate(timescape_ingester_walker_queue_size{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Ingester walker"
    },
    {
     "expr": "sum(rate(timescape_ingester_inserter_queue_size{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Ingester inserter"
    }
   ]
  },
  {
   "title": "Ingestion Rates - $event_types_not_unknown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "repeat": "event_types_not_unknown",
   "collapsed": true,
   "panels": [
    {
     "title": "Current ingest rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum by (event_type) (rate(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",event_type=~\"$event_types_not_unknown\"}[$__rate_interval]))",
       "legendFormat": "$event_types_not_unknown ingested"
      }
     ]
    },
    {
     "title": "Ingest rate 1d avg vs 7d avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum(rate(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",event_type=~\"$event_types_not_unknown\"}[1d]))",
       "legendFormat": "$event_types_not_unknown 1 day"
      },
      {
       "expr": "sum(rate(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", event_type=~\"$event_types_not_unknown\"}[1w]))",
       "legendFormat": "$event_types_not_unknown 7 days"
      }
     ]
    },
    {
     "title": "Ingest rate this week vs last week",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum by (event_type) (rate(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", event_type=~\"$event_types_not_unknown\"}[1w]))",
       "legendFormat": "$event_types_not_unknown - this week"
      },
      {
       "expr": "sum by (event_type) (rate(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", event_type=~\"$event_types_not_unknown\"}[1w] offset 1w))",
       "legendFormat": "$event_types_not_unknown - last week"
      }
     ]
    },
    {
     "title": "Event Staleness",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() - (max by (event_type) (max_over_time(timescape_ingester_inserter_last_event_timestamp{cluster=~\"$cluster\", namespace=~\"$namespace\",event_type=~\"$event_types_not_unknown\"}[1h])) != 0)",
       "legendFormat": "$event_types_not_unknown staleness"
      }
     ]
    }
   ]
  },
  {
   "title": "Export Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flow Export Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2420 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum by (event_type) (rate(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",event_type=\"flows\"}[$__rate_interval]))",
       "legendFormat": "flows ingested"
      },
      {
       "expr": "sum(rate(hubble_flows_exported_total{cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "flows exported"
      }
     ]
    }
   ]
  },
  {
   "title": "Lister",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "ListBucket API calls",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2431 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(timescape_ingester_lister_bucket_lists_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "list calls"
      }
     ]
    },
    {
     "title": "Bucket Objects Listed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2431 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(timescape_ingester_lister_objects_listed_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__range]))",
       "legendFormat": "object list rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Filter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filter Processed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3293 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(timescape_ingester_filter_processed_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "processed"
      }
     ]
    },
    {
     "title": "Filter skipped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3293 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(timescape_ingester_filter_skipped_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "skipped"
      }
     ]
    },
    {
     "title": "Filter errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3293 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(timescape_ingester_filter_errors_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Filter Batch Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3301 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (event_type) (rate(timescape_ingester_filter_batch_duration_seconds_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) / sum by (event_type) (rate(timescape_ingester_filter_batch_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le, event_type) (rate(timescape_ingester_filter_batch_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le, event_type) (rate(timescape_ingester_filter_batch_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Filter Batch Info Query Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3309 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (event_type) (rate(timescape_ingester_ingestlog_getinfo_query_duration_seconds_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) / sum by (event_type) (rate(timescape_ingester_ingestlog_getinfo_query_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le, event_type) (rate(timescape_ingester_ingestlog_getinfo_query_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le, event_type) (rate(timescape_ingester_ingestlog_getinfo_query_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  {
   "title": "Walker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Walker Tasks Running",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(avg_over_time(timescape_ingester_walker_tasks_running{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "tasks running"
      }
     ]
    },
    {
     "title": "Walker Tasks Submitted vs Failed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(timescape_ingester_walker_tasks_submitted_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "tasks submitted"
      },
      {
       "expr": "sum(rate(timescape_ingester_walker_tasks_failed_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "tasks failed"
      }
     ]
    },
    {
     "title": "Walker Bytes Downloaded per Object",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(timescape_ingester_walker_task_downloaded_bytes_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) / sum(rate(timescape_ingester_walker_task_downloaded_bytes_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(timescape_ingester_walker_task_downloaded_bytes_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(timescape_ingester_walker_task_downloaded_bytes_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Walker Duration per Object",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(timescape_ingester_walker_task_duration_seconds_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) / sum(rate(timescape_ingester_walker_task_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(timescape_ingester_walker_task_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(timescape_ingester_walker_task_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Walker Bytes Downloaded Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(timescape_ingester_walker_task_downloaded_bytes_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "bytes read"
      }
     ]
    }
   ]
  },
  {
   "title": "Push API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Push API Bytes Uploaded per File",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3313 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(timescape_ingester_push_file_received_bytes_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) / sum(rate(timescape_ingester_push_file_received_bytes_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(timescape_ingester_push_file_received_bytes_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(timescape_ingester_push_file_received_bytes_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Push API Upload duration per File",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3313 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(timescape_ingester_push_file_upload_duration_seconds_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) / sum(rate(timescape_ingester_push_file_upload_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(timescape_ingester_push_file_upload_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(timescape_ingester_push_file_upload_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Push API Bytes Uploaded Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3321 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(timescape_ingester_push_file_received_bytes_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "bytes read"
      }
     ]
    }
   ]
  },
  { "title": "$ingestion_source decoder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }, "repeat": "ingestion_source" },
  {
   "title": "$ingestion_source Events Decoded Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by (event_type, state) (rate(timescape_ingester_decoder_decoded_events_sum{cluster=~\"$cluster\",namespace=~\"$namespace\",event_type=~\"$event_types\",source=\"$ingestion_source\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ event_type }} decode {{ state }}"
    }
   ]
  },
  {
   "title": "$ingestion_source Bytes Decoded Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(timescape_ingester_decoder_file_decoded_bytes_sum{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\"}[$__rate_interval]))",
     "legendFormat": "bytes read"
    }
   ]
  },
  {
   "title": "$ingestion_source Events Decoded Per File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(timescape_ingester_decoder_decoded_events_sum{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\",event_type!=\"unknown\"}[$__rate_interval])) / sum(rate(timescape_ingester_decoder_decoded_events_count{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\",event_type!=\"unknown\"}[$__rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(timescape_ingester_decoder_decoded_events_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\",event_type!=\"unknown\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(timescape_ingester_decoder_decoded_events_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\",event_type!=\"unknown\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "$ingestion_source Lines Read Per File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum(rate(timescape_ingester_decoder_file_read_lines_sum{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\"}[$__rate_interval])) / sum(rate(timescape_ingester_decoder_file_read_lines_count{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\"}[$__rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(timescape_ingester_decoder_file_read_lines_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(timescape_ingester_decoder_file_read_lines_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "$ingestion_source Bytes Decoded per File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(timescape_ingester_decoder_file_decoded_bytes_sum{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\"}[$__rate_interval])) / sum(rate(timescape_ingester_decoder_file_decoded_bytes_count{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\"}[$__rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(timescape_ingester_decoder_file_decoded_bytes_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(timescape_ingester_decoder_file_decoded_bytes_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "$ingestion_source JSON Decode duration per File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(timescape_ingester_decoder_file_json_decode_duration_seconds_sum{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\"}[$__rate_interval])) / sum(rate(timescape_ingester_decoder_file_json_decode_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(timescape_ingester_decoder_file_json_decode_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(timescape_ingester_decoder_file_json_decode_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",source=\"$ingestion_source\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "$ingestion_source Inserter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 }, "repeat": "ingestion_source" },
  {
   "title": "Inserter events ingested total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by (event_type) (rate(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\",namespace=~\"$namespace\",event_type=~\"$event_types\",event_type!=\"unknown\", source=~\"$ingestion_source\"}[$__rate_interval]))",
     "legendFormat": "{{ event_type }} ingest rate"
    }
   ]
  },
  {
   "title": "Inserter events ingested per batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(timescape_ingester_inserter_events_ingested_sum{cluster=~\"$cluster\",namespace=~\"$namespace\", source=~\"$ingestion_source\"}[$__rate_interval])) / sum(rate(timescape_ingester_inserter_events_ingested_count{cluster=~\"$cluster\",namespace=~\"$namespace\", source=~\"$ingestion_source\"}[$__rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(timescape_ingester_inserter_events_ingested_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\", source=~\"$ingestion_source\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(timescape_ingester_inserter_events_ingested_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\", source=~\"$ingestion_source\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Inserter Batch Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(timescape_ingester_inserter_event_batch_duration_seconds_sum{cluster=~\"$cluster\",namespace=~\"$namespace\", source=~\"$ingestion_source\"}[$__rate_interval])) / sum(rate(timescape_ingester_inserter_event_batch_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\", source=~\"$ingestion_source\"}[$__rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(timescape_ingester_inserter_event_batch_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\", source=~\"$ingestion_source\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(timescape_ingester_inserter_event_batch_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\", source=~\"$ingestion_source\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Ingest Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingest Log Update Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(timescape_ingester_ingestlog_updateinfo_query_duration_seconds_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) / sum(rate(timescape_ingester_ingestlog_updateinfo_query_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(timescape_ingester_ingestlog_updateinfo_query_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(timescape_ingester_ingestlog_updateinfo_query_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Ingest Log Updates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "targets": [
      {
       "expr": "sum(rate(timescape_ingester_ingestlog_updateinfo_query_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Updates"
      }
     ]
    }
   ]
  }
 ]
}