{
 "title": "Timescape Server",
 "tags": [ "hubble-timescape" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(timescape_build_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(timescape_build_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "gRPC queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total queries",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{cluster=~\"$cluster\",namespace=~\"$namespace\", job=\"hubble-timescape-server-metrics\"}[$__range])) by (grpc_service, grpc_method) > 0",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Total queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{cluster=~\"$cluster\",namespace=~\"$namespace\", job=\"hubble-timescape-server-metrics\"}[$__rate_interval])) by (grpc_service, grpc_method) > 0",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Failed queries by reason",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{cluster=~\"$cluster\",namespace=~\"$namespace\", job=\"hubble-timescape-server-metrics\", grpc_code!=\"OK\"}[$__range])) by (grpc_service, grpc_method, grpc_code) > 0",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}, {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Failed queries by reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{cluster=~\"$cluster\",namespace=~\"$namespace\", job=\"hubble-timescape-server-metrics\", grpc_code!=\"OK\"}[$__rate_interval])) by (grpc_service, grpc_method, grpc_code) > 0",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}, {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Database Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total queries",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(db_queries_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__range])) by (query_name) > 0",
     "legendFormat": "{{query_name}}"
    }
   ]
  },
  {
   "title": "Total queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(db_queries_duration_seconds_count{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (query_name) > 0",
     "legendFormat": "{{query_name}}"
    }
   ]
  },
  {
   "title": "Failed queries by reason",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(db_queries_duration_seconds_count{status=\"error\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__range])) by (query_name, reason) > 0",
     "legendFormat": "{{query_name}}, reason: {{reason}}"
    }
   ]
  },
  {
   "title": "Failed queries by reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(db_queries_duration_seconds_count{status=\"error\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (query_name, reason) > 0",
     "legendFormat": "{{query_name}}, reason: {{reason}}"
    }
   ]
  },
  {
   "title": "Average successful query duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(db_queries_duration_seconds_sum{status=\"ok\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__range])) by (query_name)/sum(increase(db_queries_duration_seconds_count{status=\"ok\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__range])) by (query_name)) > 0",
     "legendFormat": "{{query_name}}"
    }
   ]
  },
  {
   "title": "Average successful query duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(db_queries_duration_seconds_sum{status=\"ok\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (query_name)/ sum(rate(db_queries_duration_seconds_count{status=\"ok\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (query_name)) > 0",
     "legendFormat": "{{query_name}}"
    }
   ]
  },
  {
   "title": "Median successful query duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(increase(db_queries_duration_seconds_bucket{status=\"ok\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__range])) by (le, query_name)) > 0",
     "legendFormat": "{{query_name}}"
    }
   ]
  },
  {
   "title": "Median successful query duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(db_queries_duration_seconds_bucket{status=\"ok\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (le, query_name)) > 0",
     "legendFormat": "{{query_name}}"
    }
   ]
  },
  {
   "title": "90th percentile successful query duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(increase(db_queries_duration_seconds_bucket{status=\"ok\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__range])) by (le, query_name)) > 0",
     "legendFormat": "{{query_name}}"
    }
   ]
  },
  {
   "title": "90th percentile successful query duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(db_queries_duration_seconds_bucket{status=\"ok\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (le, query_name)) > 0",
     "legendFormat": "{{query_name}}"
    }
   ]
  }
 ]
}