// Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of
// Isovalent Inc and its suppliers, if any. The intellectual and technical
// concepts contained herein are proprietary to Isovalent Inc and its suppliers
// and may be covered by U.S. and Foreign Patents, patents in process, and are
// protected by trade secret or copyright law.  Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written
// permission is obtained from Isovalent Inc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: v1/service_health.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_v1_service_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_health_proto_rawDescGZIP(), []int{0}
}

type WatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FullSnapshot indicates that the events field contains the full current
	// table contents. Subsequent messages contain incremental updates.
	FullSnapshot  bool                   `protobuf:"varint,1,opt,name=full_snapshot,json=fullSnapshot,proto3" json:"full_snapshot,omitempty"`
	Events        []*WatchResponse_Event `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_v1_service_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_health_proto_rawDescGZIP(), []int{1}
}

func (x *WatchResponse) GetFullSnapshot() bool {
	if x != nil {
		return x.FullSnapshot
	}
	return false
}

func (x *WatchResponse) GetEvents() []*WatchResponse_Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type WatchResponse_Event struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespace       string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Healthy         bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	HealthyBackends int32                  `protobuf:"varint,4,opt,name=healthy_backends,json=healthyBackends,proto3" json:"healthy_backends,omitempty"`
	TotalBackends   int32                  `protobuf:"varint,5,opt,name=total_backends,json=totalBackends,proto3" json:"total_backends,omitempty"`
	MinHealthyPct   uint32                 `protobuf:"varint,6,opt,name=min_healthy_pct,json=minHealthyPct,proto3" json:"min_healthy_pct,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Deleted         bool                   `protobuf:"varint,9,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchResponse_Event) Reset() {
	*x = WatchResponse_Event{}
	mi := &file_v1_service_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse_Event) ProtoMessage() {}

func (x *WatchResponse_Event) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse_Event.ProtoReflect.Descriptor instead.
func (*WatchResponse_Event) Descriptor() ([]byte, []int) {
	return file_v1_service_health_proto_rawDescGZIP(), []int{1, 0}
}

func (x *WatchResponse_Event) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WatchResponse_Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WatchResponse_Event) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *WatchResponse_Event) GetHealthyBackends() int32 {
	if x != nil {
		return x.HealthyBackends
	}
	return 0
}

func (x *WatchResponse_Event) GetTotalBackends() int32 {
	if x != nil {
		return x.TotalBackends
	}
	return 0
}

func (x *WatchResponse_Event) GetMinHealthyPct() uint32 {
	if x != nil {
		return x.MinHealthyPct
	}
	return 0
}

func (x *WatchResponse_Event) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *WatchResponse_Event) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *WatchResponse_Event) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_v1_service_health_proto protoreflect.FileDescriptor

const file_v1_service_health_proto_rawDesc = "" +
	"\n" +
	"\x17v1/service_health.proto\x12\x12t2servicehealth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0e\n" +
	"\fWatchRequest\"\xd5\x03\n" +
	"\rWatchResponse\x12#\n" +
	"\rfull_snapshot\x18\x01 \x01(\bR\ffullSnapshot\x12?\n" +
	"\x06events\x18\x02 \x03(\v2'.t2servicehealth.v1.WatchResponse.EventR\x06events\x1a\xdd\x02\n" +
	"\x05Event\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12)\n" +
	"\x10healthy_backends\x18\x04 \x01(\x05R\x0fhealthyBackends\x12%\n" +
	"\x0etotal_backends\x18\x05 \x01(\x05R\rtotalBackends\x12&\n" +
	"\x0fmin_healthy_pct\x18\x06 \x01(\rR\rminHealthyPct\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\adeleted\x18\t \x01(\bR\adeleted2a\n" +
	"\rServiceHealth\x12P\n" +
	"\x05Watch\x12 .t2servicehealth.v1.WatchRequest\x1a!.t2servicehealth.v1.WatchResponse\"\x000\x01BCZAgithub.com/cilium/cilium/enterprise/pkg/lb/t2servicehealth/api/v1b\x06proto3"

var (
	file_v1_service_health_proto_rawDescOnce sync.Once
	file_v1_service_health_proto_rawDescData []byte
)

func file_v1_service_health_proto_rawDescGZIP() []byte {
	file_v1_service_health_proto_rawDescOnce.Do(func() {
		file_v1_service_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_service_health_proto_rawDesc), len(file_v1_service_health_proto_rawDesc)))
	})
	return file_v1_service_health_proto_rawDescData
}

var file_v1_service_health_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_service_health_proto_goTypes = []any{
	(*WatchRequest)(nil),          // 0: t2servicehealth.v1.WatchRequest
	(*WatchResponse)(nil),         // 1: t2servicehealth.v1.WatchResponse
	(*WatchResponse_Event)(nil),   // 2: t2servicehealth.v1.WatchResponse.Event
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_v1_service_health_proto_depIdxs = []int32{
	2, // 0: t2servicehealth.v1.WatchResponse.events:type_name -> t2servicehealth.v1.WatchResponse.Event
	3, // 1: t2servicehealth.v1.WatchResponse.Event.updated_at:type_name -> google.protobuf.Timestamp
	3, // 2: t2servicehealth.v1.WatchResponse.Event.expires_at:type_name -> google.protobuf.Timestamp
	0, // 3: t2servicehealth.v1.ServiceHealth.Watch:input_type -> t2servicehealth.v1.WatchRequest
	1, // 4: t2servicehealth.v1.ServiceHealth.Watch:output_type -> t2servicehealth.v1.WatchResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_service_health_proto_init() }
func file_v1_service_health_proto_init() {
	if File_v1_service_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_service_health_proto_rawDesc), len(file_v1_service_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_service_health_proto_goTypes,
		DependencyIndexes: file_v1_service_health_proto_depIdxs,
		MessageInfos:      file_v1_service_health_proto_msgTypes,
	}.Build()
	File_v1_service_health_proto = out.File
	file_v1_service_health_proto_goTypes = nil
	file_v1_service_health_proto_depIdxs = nil
}
