// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IsovalentCoreVRFLister helps list IsovalentCoreVRFs.
// All objects returned here must be treated as read-only.
type IsovalentCoreVRFLister interface {
	// List lists all IsovalentCoreVRFs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*isovalentcomv1alpha1.IsovalentCoreVRF, err error)
	// Get retrieves the IsovalentCoreVRF from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*isovalentcomv1alpha1.IsovalentCoreVRF, error)
	IsovalentCoreVRFListerExpansion
}

// isovalentCoreVRFLister implements the IsovalentCoreVRFLister interface.
type isovalentCoreVRFLister struct {
	listers.ResourceIndexer[*isovalentcomv1alpha1.IsovalentCoreVRF]
}

// NewIsovalentCoreVRFLister returns a new IsovalentCoreVRFLister.
func NewIsovalentCoreVRFLister(indexer cache.Indexer) IsovalentCoreVRFLister {
	return &isovalentCoreVRFLister{listers.New[*isovalentcomv1alpha1.IsovalentCoreVRF](indexer, isovalentcomv1alpha1.Resource("isovalentcorevrf"))}
}
