// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IsovalentCoreVRFNodeStatusLister helps list IsovalentCoreVRFNodeStatuses.
// All objects returned here must be treated as read-only.
type IsovalentCoreVRFNodeStatusLister interface {
	// List lists all IsovalentCoreVRFNodeStatuses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus, err error)
	// Get retrieves the IsovalentCoreVRFNodeStatus from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus, error)
	IsovalentCoreVRFNodeStatusListerExpansion
}

// isovalentCoreVRFNodeStatusLister implements the IsovalentCoreVRFNodeStatusLister interface.
type isovalentCoreVRFNodeStatusLister struct {
	listers.ResourceIndexer[*isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus]
}

// NewIsovalentCoreVRFNodeStatusLister returns a new IsovalentCoreVRFNodeStatusLister.
func NewIsovalentCoreVRFNodeStatusLister(indexer cache.Indexer) IsovalentCoreVRFNodeStatusLister {
	return &isovalentCoreVRFNodeStatusLister{listers.New[*isovalentcomv1alpha1.IsovalentCoreVRFNodeStatus](indexer, isovalentcomv1alpha1.Resource("isovalentcorevrfnodestatus"))}
}
