// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IsovalentInspectionConfigLister helps list IsovalentInspectionConfigs.
// All objects returned here must be treated as read-only.
type IsovalentInspectionConfigLister interface {
	// List lists all IsovalentInspectionConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*isovalentcomv1alpha1.IsovalentInspectionConfig, err error)
	// Get retrieves the IsovalentInspectionConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*isovalentcomv1alpha1.IsovalentInspectionConfig, error)
	IsovalentInspectionConfigListerExpansion
}

// isovalentInspectionConfigLister implements the IsovalentInspectionConfigLister interface.
type isovalentInspectionConfigLister struct {
	listers.ResourceIndexer[*isovalentcomv1alpha1.IsovalentInspectionConfig]
}

// NewIsovalentInspectionConfigLister returns a new IsovalentInspectionConfigLister.
func NewIsovalentInspectionConfigLister(indexer cache.Indexer) IsovalentInspectionConfigLister {
	return &isovalentInspectionConfigLister{listers.New[*isovalentcomv1alpha1.IsovalentInspectionConfig](indexer, isovalentcomv1alpha1.Resource("isovalentinspectionconfig"))}
}
