- name: 'enterprise-vrf-1'
  kernel: '6.18'
  kube-proxy: 'none'
  kpr: 'true'
  devices: '{eth0,eth1}'
  secondary-network: 'true'
  tunnel: 'disabled'
  ipv6: 'true'
  enterprise-vrf: 'true'
  skip-upgrade: 'true'
