//  Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
//  NOTICE: All information contained herein is, and remains the property of
//  Isovalent Inc and its suppliers, if any. The intellectual and technical
//  concepts contained herein are proprietary to Isovalent Inc and its suppliers
//  and may be covered by U.S. and Foreign Patents, patents in process, and are
//  protected by trade secret or copyright law.  Dissemination of this information
//  or reproduction of this material is strictly forbidden unless prior written
//  permission is obtained from Isovalent Inc.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: v1/migration.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Migration_Migrate_FullMethodName = "/api.Migration/Migrate"
)

// MigrationClient is the client API for Migration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The migration service provides transfer of connection tracking state and DHCP leases
// from one Cilium node to another for seamless live migration of VMs without disrupting
// existing connections.
//
// The target node detects that a VM is being migrated to it (e.g. from kubevirt annotations
// on a pod) and calls Migrate() on the source node to request transfer of the state.
//
// MigrationStart message initiates the transfer and the source node streams one or more
// batches of state. When the target node has detected that the VM migration has finished
// it requests a final delta with a MigrationFinalize message. The source node will then
// send one or more batches and close the stream.
type MigrationClient interface {
	// Migrate opens a workload migration stream.
	Migrate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MigrationRequest, MigrationBatch], error)
}

type migrationClient struct {
	cc grpc.ClientConnInterface
}

func NewMigrationClient(cc grpc.ClientConnInterface) MigrationClient {
	return &migrationClient{cc}
}

func (c *migrationClient) Migrate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MigrationRequest, MigrationBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Migration_ServiceDesc.Streams[0], Migration_Migrate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MigrationRequest, MigrationBatch]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Migration_MigrateClient = grpc.BidiStreamingClient[MigrationRequest, MigrationBatch]

// MigrationServer is the server API for Migration service.
// All implementations must embed UnimplementedMigrationServer
// for forward compatibility.
//
// The migration service provides transfer of connection tracking state and DHCP leases
// from one Cilium node to another for seamless live migration of VMs without disrupting
// existing connections.
//
// The target node detects that a VM is being migrated to it (e.g. from kubevirt annotations
// on a pod) and calls Migrate() on the source node to request transfer of the state.
//
// MigrationStart message initiates the transfer and the source node streams one or more
// batches of state. When the target node has detected that the VM migration has finished
// it requests a final delta with a MigrationFinalize message. The source node will then
// send one or more batches and close the stream.
type MigrationServer interface {
	// Migrate opens a workload migration stream.
	Migrate(grpc.BidiStreamingServer[MigrationRequest, MigrationBatch]) error
	mustEmbedUnimplementedMigrationServer()
}

// UnimplementedMigrationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMigrationServer struct{}

func (UnimplementedMigrationServer) Migrate(grpc.BidiStreamingServer[MigrationRequest, MigrationBatch]) error {
	return status.Error(codes.Unimplemented, "method Migrate not implemented")
}
func (UnimplementedMigrationServer) mustEmbedUnimplementedMigrationServer() {}
func (UnimplementedMigrationServer) testEmbeddedByValue()                   {}

// UnsafeMigrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigrationServer will
// result in compilation errors.
type UnsafeMigrationServer interface {
	mustEmbedUnimplementedMigrationServer()
}

func RegisterMigrationServer(s grpc.ServiceRegistrar, srv MigrationServer) {
	// If the following call panics, it indicates UnimplementedMigrationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Migration_ServiceDesc, srv)
}

func _Migration_Migrate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MigrationServer).Migrate(&grpc.GenericServerStream[MigrationRequest, MigrationBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Migration_MigrateServer = grpc.BidiStreamingServer[MigrationRequest, MigrationBatch]

// Migration_ServiceDesc is the grpc.ServiceDesc for Migration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Migration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Migration",
	HandlerType: (*MigrationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Migrate",
			Handler:       _Migration_Migrate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "v1/migration.proto",
}
