//  Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
//  NOTICE: All information contained herein is, and remains the property of
//  Isovalent Inc and its suppliers, if any. The intellectual and technical
//  concepts contained herein are proprietary to Isovalent Inc and its suppliers
//  and may be covered by U.S. and Foreign Patents, patents in process, and are
//  protected by trade secret or copyright law.  Dissemination of this information
//  or reproduction of this material is strictly forbidden unless prior written
//  permission is obtained from Isovalent Inc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v1/migration.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CTMapKind int32

const (
	CTMapKind_CT_MAP_KIND_UNSPECIFIED  CTMapKind = 0
	CTMapKind_CT_MAP_KIND_GLOBAL_TCP4  CTMapKind = 1
	CTMapKind_CT_MAP_KIND_GLOBAL_ANY4  CTMapKind = 2
	CTMapKind_CT_MAP_KIND_GLOBAL_TCP6  CTMapKind = 3
	CTMapKind_CT_MAP_KIND_GLOBAL_ANY6  CTMapKind = 4
	CTMapKind_CT_MAP_KIND_PRIVNET_TCP4 CTMapKind = 5
	CTMapKind_CT_MAP_KIND_PRIVNET_ANY4 CTMapKind = 6
	CTMapKind_CT_MAP_KIND_PRIVNET_TCP6 CTMapKind = 7
	CTMapKind_CT_MAP_KIND_PRIVNET_ANY6 CTMapKind = 8
)

// Enum value maps for CTMapKind.
var (
	CTMapKind_name = map[int32]string{
		0: "CT_MAP_KIND_UNSPECIFIED",
		1: "CT_MAP_KIND_GLOBAL_TCP4",
		2: "CT_MAP_KIND_GLOBAL_ANY4",
		3: "CT_MAP_KIND_GLOBAL_TCP6",
		4: "CT_MAP_KIND_GLOBAL_ANY6",
		5: "CT_MAP_KIND_PRIVNET_TCP4",
		6: "CT_MAP_KIND_PRIVNET_ANY4",
		7: "CT_MAP_KIND_PRIVNET_TCP6",
		8: "CT_MAP_KIND_PRIVNET_ANY6",
	}
	CTMapKind_value = map[string]int32{
		"CT_MAP_KIND_UNSPECIFIED":  0,
		"CT_MAP_KIND_GLOBAL_TCP4":  1,
		"CT_MAP_KIND_GLOBAL_ANY4":  2,
		"CT_MAP_KIND_GLOBAL_TCP6":  3,
		"CT_MAP_KIND_GLOBAL_ANY6":  4,
		"CT_MAP_KIND_PRIVNET_TCP4": 5,
		"CT_MAP_KIND_PRIVNET_ANY4": 6,
		"CT_MAP_KIND_PRIVNET_TCP6": 7,
		"CT_MAP_KIND_PRIVNET_ANY6": 8,
	}
)

func (x CTMapKind) Enum() *CTMapKind {
	p := new(CTMapKind)
	*p = x
	return p
}

func (x CTMapKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CTMapKind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_migration_proto_enumTypes[0].Descriptor()
}

func (CTMapKind) Type() protoreflect.EnumType {
	return &file_v1_migration_proto_enumTypes[0]
}

func (x CTMapKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CTMapKind.Descriptor instead.
func (CTMapKind) EnumDescriptor() ([]byte, []int) {
	return file_v1_migration_proto_rawDescGZIP(), []int{0}
}

type MigrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*MigrationRequest_Start
	//	*MigrationRequest_Finalize
	Event         isMigrationRequest_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationRequest) Reset() {
	*x = MigrationRequest{}
	mi := &file_v1_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationRequest) ProtoMessage() {}

func (x *MigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationRequest.ProtoReflect.Descriptor instead.
func (*MigrationRequest) Descriptor() ([]byte, []int) {
	return file_v1_migration_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationRequest) GetEvent() isMigrationRequest_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *MigrationRequest) GetStart() *MigrationStart {
	if x != nil {
		if x, ok := x.Event.(*MigrationRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *MigrationRequest) GetFinalize() *MigrationFinalize {
	if x != nil {
		if x, ok := x.Event.(*MigrationRequest_Finalize); ok {
			return x.Finalize
		}
	}
	return nil
}

type isMigrationRequest_Event interface {
	isMigrationRequest_Event()
}

type MigrationRequest_Start struct {
	// Start migration of the workload state. The server will start
	// streaming batches or fails with NOT_FOUND if the workload is not
	// known.
	Start *MigrationStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type MigrationRequest_Finalize struct {
	// Finalize migration of the workload state. This requests for the final batch
	// to be sent after which the stream is closed by the server.
	Finalize *MigrationFinalize `protobuf:"bytes,2,opt,name=finalize,proto3,oneof"`
}

func (*MigrationRequest_Start) isMigrationRequest_Event() {}

func (*MigrationRequest_Finalize) isMigrationRequest_Event() {}

type MigrationStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Private network of the workload to migrate.
	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// MAC address of the workload to migrate.
	Mac           string `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationStart) Reset() {
	*x = MigrationStart{}
	mi := &file_v1_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationStart) ProtoMessage() {}

func (x *MigrationStart) ProtoReflect() protoreflect.Message {
	mi := &file_v1_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationStart.ProtoReflect.Descriptor instead.
func (*MigrationStart) Descriptor() ([]byte, []int) {
	return file_v1_migration_proto_rawDescGZIP(), []int{1}
}

func (x *MigrationStart) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *MigrationStart) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type MigrationFinalize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationFinalize) Reset() {
	*x = MigrationFinalize{}
	mi := &file_v1_migration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationFinalize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationFinalize) ProtoMessage() {}

func (x *MigrationFinalize) ProtoReflect() protoreflect.Message {
	mi := &file_v1_migration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationFinalize.ProtoReflect.Descriptor instead.
func (*MigrationFinalize) Descriptor() ([]byte, []int) {
	return file_v1_migration_proto_rawDescGZIP(), []int{2}
}

type MigrationBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection tracking records.
	Records []*CTRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// DHCP leases.
	DhcpLease     []*DHCPLease `protobuf:"bytes,2,rep,name=dhcp_lease,json=dhcpLease,proto3" json:"dhcp_lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationBatch) Reset() {
	*x = MigrationBatch{}
	mi := &file_v1_migration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationBatch) ProtoMessage() {}

func (x *MigrationBatch) ProtoReflect() protoreflect.Message {
	mi := &file_v1_migration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationBatch.ProtoReflect.Descriptor instead.
func (*MigrationBatch) Descriptor() ([]byte, []int) {
	return file_v1_migration_proto_rawDescGZIP(), []int{3}
}

func (x *MigrationBatch) GetRecords() []*CTRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *MigrationBatch) GetDhcpLease() []*DHCPLease {
	if x != nil {
		return x.DhcpLease
	}
	return nil
}

type CTRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map kind
	Kind CTMapKind `protobuf:"varint,1,opt,name=kind,proto3,enum=api.CTMapKind" json:"kind,omitempty"`
	// Private network name or empty if kind is a global map
	Network string `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	// Connection tracking key
	Key *CTKey `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// Connection tracking value
	Value         *CTValue `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTRecord) Reset() {
	*x = CTRecord{}
	mi := &file_v1_migration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTRecord) ProtoMessage() {}

func (x *CTRecord) ProtoReflect() protoreflect.Message {
	mi := &file_v1_migration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTRecord.ProtoReflect.Descriptor instead.
func (*CTRecord) Descriptor() ([]byte, []int) {
	return file_v1_migration_proto_rawDescGZIP(), []int{4}
}

func (x *CTRecord) GetKind() CTMapKind {
	if x != nil {
		return x.Kind
	}
	return CTMapKind_CT_MAP_KIND_UNSPECIFIED
}

func (x *CTRecord) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *CTRecord) GetKey() *CTKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CTRecord) GetValue() *CTValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// Connection tracking key. Counterpart of [ctmap.CtKey*].
type CTKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source IP address. In the private network CT maps this is the network IP
	// and in the global CT maps this is a pod IP.
	SourceIp []byte `protobuf:"bytes,1,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	// Destination IP address. In the private network CT maps this is the network IP
	// and in the global CT maps this is a pod IP.
	DestIp []byte `protobuf:"bytes,2,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	// Source port number
	SourcePort uint32 `protobuf:"varint,3,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	// Destination port number
	DestPort uint32 `protobuf:"varint,4,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	// Type of the next protocol after IP, e.g. IPPROTO_TCP (6), IPPROTO_UDP (17) etc.
	NextHeader uint32 `protobuf:"varint,5,opt,name=next_header,json=nextHeader,proto3" json:"next_header,omitempty"`
	// Tuple flags as specified in pkg/tuple, e.g. TUPLE_F_{OUT,IN,RELATED,SERVICE}
	Flags         uint32 `protobuf:"varint,6,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTKey) Reset() {
	*x = CTKey{}
	mi := &file_v1_migration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTKey) ProtoMessage() {}

func (x *CTKey) ProtoReflect() protoreflect.Message {
	mi := &file_v1_migration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTKey.ProtoReflect.Descriptor instead.
func (*CTKey) Descriptor() ([]byte, []int) {
	return file_v1_migration_proto_rawDescGZIP(), []int{5}
}

func (x *CTKey) GetSourceIp() []byte {
	if x != nil {
		return x.SourceIp
	}
	return nil
}

func (x *CTKey) GetDestIp() []byte {
	if x != nil {
		return x.DestIp
	}
	return nil
}

func (x *CTKey) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *CTKey) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *CTKey) GetNextHeader() uint32 {
	if x != nil {
		return x.NextHeader
	}
	return 0
}

func (x *CTKey) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

// Connection tracking state to be migrated.
// Counterpart to [ctmap.CtValue]. Only fields that can be migrated
// are present (e.g. proxy and LB fields not included).
type CTValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Remaining lifetime for the entry.
	Lifetime *durationpb.Duration `protobuf:"bytes,1,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	// Flags. See 'struct ct_entry' in bpf/lib/conntrack.h for definition.
	Flags uint32 `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	// "OR" of TCP flags seen in transmit direction.
	TxFlagsSeen uint32 `protobuf:"varint,3,opt,name=tx_flags_seen,json=txFlagsSeen,proto3" json:"tx_flags_seen,omitempty"`
	// "OR" of TCP flags seen in receive direction.
	RxFlagsSeen   uint32 `protobuf:"varint,4,opt,name=rx_flags_seen,json=rxFlagsSeen,proto3" json:"rx_flags_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTValue) Reset() {
	*x = CTValue{}
	mi := &file_v1_migration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTValue) ProtoMessage() {}

func (x *CTValue) ProtoReflect() protoreflect.Message {
	mi := &file_v1_migration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTValue.ProtoReflect.Descriptor instead.
func (*CTValue) Descriptor() ([]byte, []int) {
	return file_v1_migration_proto_rawDescGZIP(), []int{6}
}

func (x *CTValue) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *CTValue) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *CTValue) GetTxFlagsSeen() uint32 {
	if x != nil {
		return x.TxFlagsSeen
	}
	return 0
}

func (x *CTValue) GetRxFlagsSeen() uint32 {
	if x != nil {
		return x.RxFlagsSeen
	}
	return 0
}

type DHCPLease struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IPv4 address.
	Ipv4 []byte `protobuf:"bytes,1,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	// The DHCP server identity (e.g. IP address).
	ServerId string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// The time at which the lease was obtained.
	ObtainedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=obtained_at,json=obtainedAt,proto3" json:"obtained_at,omitempty"`
	// The time at which the lease should be renewed.
	RenewAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=renew_at,json=renewAt,proto3" json:"renew_at,omitempty"`
	// The time at which the lease expires.
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DHCPLease) Reset() {
	*x = DHCPLease{}
	mi := &file_v1_migration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DHCPLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHCPLease) ProtoMessage() {}

func (x *DHCPLease) ProtoReflect() protoreflect.Message {
	mi := &file_v1_migration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHCPLease.ProtoReflect.Descriptor instead.
func (*DHCPLease) Descriptor() ([]byte, []int) {
	return file_v1_migration_proto_rawDescGZIP(), []int{7}
}

func (x *DHCPLease) GetIpv4() []byte {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *DHCPLease) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DHCPLease) GetObtainedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObtainedAt
	}
	return nil
}

func (x *DHCPLease) GetRenewAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RenewAt
	}
	return nil
}

func (x *DHCPLease) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

var File_v1_migration_proto protoreflect.FileDescriptor

const file_v1_migration_proto_rawDesc = "" +
	"\n" +
	"\x12v1/migration.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"~\n" +
	"\x10MigrationRequest\x12+\n" +
	"\x05start\x18\x01 \x01(\v2\x13.api.MigrationStartH\x00R\x05start\x124\n" +
	"\bfinalize\x18\x02 \x01(\v2\x16.api.MigrationFinalizeH\x00R\bfinalizeB\a\n" +
	"\x05event\"<\n" +
	"\x0eMigrationStart\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\"\x13\n" +
	"\x11MigrationFinalize\"h\n" +
	"\x0eMigrationBatch\x12'\n" +
	"\arecords\x18\x01 \x03(\v2\r.api.CTRecordR\arecords\x12-\n" +
	"\n" +
	"dhcp_lease\x18\x02 \x03(\v2\x0e.api.DHCPLeaseR\tdhcpLease\"\x8a\x01\n" +
	"\bCTRecord\x12\"\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x0e.api.CTMapKindR\x04kind\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x1c\n" +
	"\x03key\x18\x03 \x01(\v2\n" +
	".api.CTKeyR\x03key\x12\"\n" +
	"\x05value\x18\x04 \x01(\v2\f.api.CTValueR\x05value\"\xb2\x01\n" +
	"\x05CTKey\x12\x1b\n" +
	"\tsource_ip\x18\x01 \x01(\fR\bsourceIp\x12\x17\n" +
	"\adest_ip\x18\x02 \x01(\fR\x06destIp\x12\x1f\n" +
	"\vsource_port\x18\x03 \x01(\rR\n" +
	"sourcePort\x12\x1b\n" +
	"\tdest_port\x18\x04 \x01(\rR\bdestPort\x12\x1f\n" +
	"\vnext_header\x18\x05 \x01(\rR\n" +
	"nextHeader\x12\x14\n" +
	"\x05flags\x18\x06 \x01(\rR\x05flags\"\x9e\x01\n" +
	"\aCTValue\x125\n" +
	"\blifetime\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\blifetime\x12\x14\n" +
	"\x05flags\x18\x02 \x01(\rR\x05flags\x12\"\n" +
	"\rtx_flags_seen\x18\x03 \x01(\rR\vtxFlagsSeen\x12\"\n" +
	"\rrx_flags_seen\x18\x04 \x01(\rR\vrxFlagsSeen\"\xe9\x01\n" +
	"\tDHCPLease\x12\x12\n" +
	"\x04ipv4\x18\x01 \x01(\fR\x04ipv4\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12;\n" +
	"\vobtained_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"obtainedAt\x125\n" +
	"\brenew_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\arenewAt\x127\n" +
	"\texpire_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt*\x94\x02\n" +
	"\tCTMapKind\x12\x1b\n" +
	"\x17CT_MAP_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CT_MAP_KIND_GLOBAL_TCP4\x10\x01\x12\x1b\n" +
	"\x17CT_MAP_KIND_GLOBAL_ANY4\x10\x02\x12\x1b\n" +
	"\x17CT_MAP_KIND_GLOBAL_TCP6\x10\x03\x12\x1b\n" +
	"\x17CT_MAP_KIND_GLOBAL_ANY6\x10\x04\x12\x1c\n" +
	"\x18CT_MAP_KIND_PRIVNET_TCP4\x10\x05\x12\x1c\n" +
	"\x18CT_MAP_KIND_PRIVNET_ANY4\x10\x06\x12\x1c\n" +
	"\x18CT_MAP_KIND_PRIVNET_TCP6\x10\a\x12\x1c\n" +
	"\x18CT_MAP_KIND_PRIVNET_ANY6\x10\b2H\n" +
	"\tMigration\x12;\n" +
	"\aMigrate\x12\x15.api.MigrationRequest\x1a\x13.api.MigrationBatch\"\x00(\x010\x01B@Z>github.com/cilium/cilium/enterprise/pkg/privnet/grpc/api/v1;v1b\x06proto3"

var (
	file_v1_migration_proto_rawDescOnce sync.Once
	file_v1_migration_proto_rawDescData []byte
)

func file_v1_migration_proto_rawDescGZIP() []byte {
	file_v1_migration_proto_rawDescOnce.Do(func() {
		file_v1_migration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_migration_proto_rawDesc), len(file_v1_migration_proto_rawDesc)))
	})
	return file_v1_migration_proto_rawDescData
}

var file_v1_migration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_migration_proto_goTypes = []any{
	(CTMapKind)(0),                // 0: api.CTMapKind
	(*MigrationRequest)(nil),      // 1: api.MigrationRequest
	(*MigrationStart)(nil),        // 2: api.MigrationStart
	(*MigrationFinalize)(nil),     // 3: api.MigrationFinalize
	(*MigrationBatch)(nil),        // 4: api.MigrationBatch
	(*CTRecord)(nil),              // 5: api.CTRecord
	(*CTKey)(nil),                 // 6: api.CTKey
	(*CTValue)(nil),               // 7: api.CTValue
	(*DHCPLease)(nil),             // 8: api.DHCPLease
	(*durationpb.Duration)(nil),   // 9: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_v1_migration_proto_depIdxs = []int32{
	2,  // 0: api.MigrationRequest.start:type_name -> api.MigrationStart
	3,  // 1: api.MigrationRequest.finalize:type_name -> api.MigrationFinalize
	5,  // 2: api.MigrationBatch.records:type_name -> api.CTRecord
	8,  // 3: api.MigrationBatch.dhcp_lease:type_name -> api.DHCPLease
	0,  // 4: api.CTRecord.kind:type_name -> api.CTMapKind
	6,  // 5: api.CTRecord.key:type_name -> api.CTKey
	7,  // 6: api.CTRecord.value:type_name -> api.CTValue
	9,  // 7: api.CTValue.lifetime:type_name -> google.protobuf.Duration
	10, // 8: api.DHCPLease.obtained_at:type_name -> google.protobuf.Timestamp
	10, // 9: api.DHCPLease.renew_at:type_name -> google.protobuf.Timestamp
	10, // 10: api.DHCPLease.expire_at:type_name -> google.protobuf.Timestamp
	1,  // 11: api.Migration.Migrate:input_type -> api.MigrationRequest
	4,  // 12: api.Migration.Migrate:output_type -> api.MigrationBatch
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_v1_migration_proto_init() }
func file_v1_migration_proto_init() {
	if File_v1_migration_proto != nil {
		return
	}
	file_v1_migration_proto_msgTypes[0].OneofWrappers = []any{
		(*MigrationRequest_Start)(nil),
		(*MigrationRequest_Finalize)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_migration_proto_rawDesc), len(file_v1_migration_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_migration_proto_goTypes,
		DependencyIndexes: file_v1_migration_proto_depIdxs,
		EnumInfos:         file_v1_migration_proto_enumTypes,
		MessageInfos:      file_v1_migration_proto_msgTypes,
	}.Build()
	File_v1_migration_proto = out.File
	file_v1_migration_proto_goTypes = nil
	file_v1_migration_proto_depIdxs = nil
}
