// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apisisovalentcomv1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1"
	versioned "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/cilium/cilium/pkg/k8s/client/informers/externalversions/internalinterfaces"
	isovalentcomv1 "github.com/cilium/cilium/pkg/k8s/client/listers/isovalent.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IsovalentEgressGatewayPolicyInformer provides access to a shared informer and lister for
// IsovalentEgressGatewayPolicies.
type IsovalentEgressGatewayPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() isovalentcomv1.IsovalentEgressGatewayPolicyLister
}

type isovalentEgressGatewayPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewIsovalentEgressGatewayPolicyInformer constructs a new informer for IsovalentEgressGatewayPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIsovalentEgressGatewayPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewIsovalentEgressGatewayPolicyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewFilteredIsovalentEgressGatewayPolicyInformer constructs a new informer for IsovalentEgressGatewayPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIsovalentEgressGatewayPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewIsovalentEgressGatewayPolicyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewIsovalentEgressGatewayPolicyInformerWithOptions constructs a new informer for IsovalentEgressGatewayPolicy type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIsovalentEgressGatewayPolicyInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	gvr := schema.GroupVersionResource{Group: "isovalent.com", Version: "v1", Resource: "isovalentegressgatewaypolicys"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.IsovalentV1().IsovalentEgressGatewayPolicies().List(context.Background(), opts)
			},
			WatchFunc: func(opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.IsovalentV1().IsovalentEgressGatewayPolicies().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.IsovalentV1().IsovalentEgressGatewayPolicies().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.IsovalentV1().IsovalentEgressGatewayPolicies().Watch(ctx, opts)
			},
		}, client),
		&apisisovalentcomv1.IsovalentEgressGatewayPolicy{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	)
}

func (f *isovalentEgressGatewayPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewIsovalentEgressGatewayPolicyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *isovalentEgressGatewayPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisisovalentcomv1.IsovalentEgressGatewayPolicy{}, f.defaultInformer)
}

func (f *isovalentEgressGatewayPolicyInformer) Lister() isovalentcomv1.IsovalentEgressGatewayPolicyLister {
	return isovalentcomv1.NewIsovalentEgressGatewayPolicyLister(f.Informer().GetIndexer())
}
