name: Enterprise Image Release Build

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*

permissions:
  # To be able to access the repository with `actions/checkout`
  contents: read
  # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
  id-token: write

jobs:
  load-versions:
    name: Load UBI base image versions
    runs-on: ubuntu-24.04
    outputs:
      ubi-minimal: ${{ steps.load.outputs.ubi-minimal }}
      ubi-micro: ${{ steps.load.outputs.ubi-micro }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Load UBI versions
        id: load
        uses: ./.github/actions/load-ubi-versions

  mirror-envoy-image:
    name: Mirror envoy image
    runs-on: ubuntu-24.04
    outputs:
      org: ${{ steps.version.outputs.org }}
      version: ${{ steps.version.outputs.envoy_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.event.push.after }}
          persist-credentials: false
          fetch-depth: 0

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Get and check version
        id: version
        env:
          # renovate: datasource=docker depName=mikefarah/yq
          yq_version: 4.53.3
        run: |
          tag=${GITHUB_REF##*/}
          echo release_tag=$tag >> $GITHUB_OUTPUT
          repo_dir=$(git rev-parse --show-toplevel)
          envoy_version=$(docker run --rm -v "${repo_dir}/install/kubernetes/cilium/values.yaml":/workdir/values.yaml --user "$(id -u):$(id -g)" mikefarah/yq:${yq_version} e ".envoy.image.tag" /workdir/values.yaml)
          echo "envoy_version=${envoy_version}" >> $GITHUB_OUTPUT
          if docker manifest inspect quay.io/${{ env.QUAY_ORGANIZATION }}/cilium-envoy-ubi:${tag} >/dev/null; then
            echo "Envoy image already exists! Copy skipped."
            echo "copy=false" >> $GITHUB_OUTPUT
          else
            echo "copy=true" >> $GITHUB_OUTPUT
          fi
          echo "org=${{ env.QUAY_ORGANIZATION }}" >> $GITHUB_OUTPUT

      - name: copy image
        uses: truemark/skopeo-copy-action@42ddf321b803e556b65006c5cdaa517bea42f548 # v1
        if: ${{ steps.version.outputs.copy == 'true' }}
        with:
          src-image: docker://quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-envoy-ubi:${{ steps.version.outputs.envoy_version }}
          dest-image: docker://quay.io/${{ env.QUAY_ORGANIZATION }}/cilium-envoy-ubi:${{ steps.version.outputs.release_tag }}
          src-username: "${{ secrets.QUAY_USERNAME_CI }}"
          src-password: "${{ secrets.QUAY_PASSWORD_CI }}"
          dest-username: "${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}"
          dest-password: "${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}"
          multi-arch: "all"

  mirror-envoy-image-artifactory:
    name: Mirror envoy image Artifactory
    runs-on: ubuntu-24.04
    outputs:
      org: ${{ steps.version.outputs.org }}
      version: ${{ steps.version.outputs.envoy_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.event.push.after }}
          persist-credentials: false
          fetch-depth: 0

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Get and check version
        id: version
        env:
          # renovate: datasource=docker depName=mikefarah/yq
          yq_version: 4.53.3
        run: |
          tag=${GITHUB_REF##*/}
          echo release_tag=$tag >> $GITHUB_OUTPUT
          repo_dir=$(git rev-parse --show-toplevel)
          envoy_version=$(docker run --rm -v "${repo_dir}/install/kubernetes/cilium/values.yaml":/workdir/values.yaml --user "$(id -u):$(id -g)" mikefarah/yq:${yq_version} e ".envoy.image.tag" /workdir/values.yaml)
          echo "envoy_version=${envoy_version}" >> $GITHUB_OUTPUT
          if docker manifest inspect ${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}/cilium-envoy-ubi:${tag} >/dev/null; then
            echo "Envoy image already exists! Copy skipped."
            echo "copy=false" >> $GITHUB_OUTPUT
          else
            echo "copy=true" >> $GITHUB_OUTPUT
          fi
          echo "org=${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}" >> $GITHUB_OUTPUT

      - name: copy image
        uses: truemark/skopeo-copy-action@42ddf321b803e556b65006c5cdaa517bea42f548 # v1
        if: ${{ steps.version.outputs.copy == 'true' }}
        with:
          src-image: docker://${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_DEV }}/cilium-envoy-ubi:${{ steps.version.outputs.envoy_version }}
          dest-image: docker://${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}/cilium-envoy-ubi:${{ steps.version.outputs.release_tag }}
          src-username: "${{ secrets.QUAY_USERNAME_CI }}"
          src-password: "${{ secrets.QUAY_PASSWORD_CI }}"
          dest-username: "${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}"
          dest-password: "${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}"
          multi-arch: "all"

  build-and-push-external-images:
    timeout-minutes: 45
    name: Build and push external images
    environment: release
    needs: load-versions
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - component: CERTGEN
            image-name: certgen-ubi
            docker-context: enterprise/images/certgen
            dockerfile: enterprise/images/certgen/Dockerfile
            base-image: ${{ needs.load-versions.outputs.ubi-micro }}

          - component: CILIUM_NODEINIT
            image-name: startup-script-ubi
            docker-context: enterprise/images/startup-script
            dockerfile: enterprise/images/startup-script/Dockerfile
            base-image: ${{ needs.load-versions.outputs.ubi-minimal }}

          - component: KUBECTL
            image-name: kubectl-ubi
            docker-context: enterprise/images/kubectl
            dockerfile: enterprise/images/kubectl/Dockerfile
            base-image: ${{ needs.load-versions.outputs.ubi-minimal }}

          - component: KUBECTL
            image-name: kubectl
            docker-context: enterprise/images/kubectl
            dockerfile: enterprise/images/kubectl/Dockerfile
            # renovate: datasource=docker
            base-image: debian:13.3-slim@sha256:f6e2cfac5cf956ea044b4bd75e6397b4372ad88fe00908045e9a0d21712ae3ba

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.event.push.after }}
          persist-credentials: false
          fetch-depth: 0

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Get and check version
        id: version
        run: |
          tag=${GITHUB_REF##*/}
          echo version=$tag >> $GITHUB_OUTPUT
          upstream_version=$(cat install/kubernetes/Makefile.values | grep ${{ matrix.component }}_VERSION | awk -F '=' '{print $2}')
          echo "upstream_version=${upstream_version}" >> $GITHUB_OUTPUT
          echo "upstream_repo=$(cat install/kubernetes/Makefile.values | grep ${{ matrix.component }}_REPO | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
          echo "upstream_digest=$(cat install/kubernetes/Makefile.values | grep ${{ matrix.component }}_DIGEST | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
          if docker manifest inspect ${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}/${{ matrix.image-name }}:${version} >/dev/null; then
            echo "Image already exists! Build skipped."
            echo "rebuild=false" >> $GITHUB_OUTPUT
          else
            echo "rebuild=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to quay.io
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}

      - name: Login to Artifactory
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ vars.ARTIFACTORY_HOST }}
          username: ${{ vars.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Login to registry.redhat.io for pulling UBI images
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Build and push ${{ matrix.component }} image
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: ${{ matrix.docker-context }}
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            quay.io/${{ env.QUAY_ORGANIZATION }}/${{ matrix.image-name }}:${{ steps.version.outputs.version }}
            ${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}/${{ matrix.image-name }}:${{ steps.version.outputs.version }}
          build-args: |
            BASE_IMAGE=${{ matrix.base-image }}
            UPSTREAM_VERSION=${{ steps.version.outputs.upstream_version }}
            UPSTREAM_IMAGE=${{ steps.version.outputs.upstream_repo }}:${{ steps.version.outputs.upstream_version }}@${{ steps.version.outputs.upstream_digest }}
            VERSION=${{ steps.version.outputs.version }}

      - name: Release ${{ matrix.component }} digest
        id: docker_digest
        shell: bash
        run: |
          digest=$(images/scripts/get-image-digest.sh ${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}/${{ matrix.image-name }}:${{ steps.version.outputs.version }})
          echo digest=${digest} >> $GITHUB_OUTPUT

      - name: Install Cosign
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Sign Container Images
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        run: |
          cosign sign -y quay.io/${{ env.QUAY_ORGANIZATION }}/${{ matrix.image-name }}:${{ steps.version.outputs.version }}@${{ steps.docker_digest.outputs.digest }}
          cosign sign -y ${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}/${{ matrix.image-name }}:${{ steps.version.outputs.version }}@${{ steps.docker_digest.outputs.digest }}

      - name: Generate SBOM
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        with:
          artifact-name: sbom_${{ matrix.image-name }}_${{ steps.version.outputs.version }}.spdx.json
          output-file: ./sbom_${{ matrix.image-name }}_${{ steps.version.outputs.version }}.spdx.json
          image: ${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}/${{ matrix.image-name }}:${{ steps.version.outputs.version }}
          upload-release-assets: false

      - name: Attach SBOM attestation to container image
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        run: |
          cosign attest -y --predicate sbom_${{ matrix.image-name }}_${{ steps.version.outputs.version }}.spdx.json --type spdxjson quay.io/${{ env.QUAY_ORGANIZATION }}/${{ matrix.image-name }}:${{ steps.version.outputs.version }}
          cosign attest -y --predicate sbom_${{ matrix.image-name }}_${{ steps.version.outputs.version }}.spdx.json --type spdxjson ${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}/${{ matrix.image-name }}:${{ steps.version.outputs.version }}

      - name: Image Release Digest
        shell: bash
        run: |
          mkdir -p image-digest/
          echo "### ${{ matrix.image-name }}" > image-digest/${{ matrix.image-name }}.txt
          echo "" >> image-digest/${{ matrix.image-name }}.txt
          echo "\`${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}/${{ matrix.image-name }}:${{ steps.version.outputs.version }}@${{ steps.docker_digest.outputs.digest }}\`" >> image-digest/${{ matrix.image-name }}.txt
          echo "" >> image-digest/${{ matrix.image-name }}.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: image-digest ${{ matrix.image-name }}
          path: image-digest

  build-and-push:
    timeout-minutes: 45
    name: Build and Push Images
    environment: release
    runs-on: ubuntu-24.04
    # The cilium-envoy image is used for building the image of the Cilium agent and should have been published beforehands
    needs: [mirror-envoy-image, mirror-envoy-image-artifactory, load-versions]
    strategy:
      matrix:
        include:
          - name: cilium
            dockerfile: ./enterprise/images/cilium/Dockerfile
            # renovate: datasource=docker
            base_image: ${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_DEV }}/cilium-runtime-ubi:0292e7be011ab44aa3de2f8aa933161d5899a563
            envoy_image: ${{ vars.ARTIFACTORY_HOST }}/${{ needs.mirror-envoy-image-artifactory.outputs.org }}/cilium-envoy-ubi:${{ needs.mirror-envoy-image-artifactory.outputs.version }}
            postfix: ubi
            image_name: cilium

          - name: operator
            dockerfile: ./enterprise/images/operator/Dockerfile
            base_image: ${{ needs.load-versions.outputs.ubi-micro }}
            postfix: ubi
            image_name: operator-generic

          - name: hubble-relay
            dockerfile: ./enterprise/images/hubble-relay/Dockerfile
            base_image: ${{ needs.load-versions.outputs.ubi-micro }}
            postfix: ubi
            image_name: hubble-relay

          - name: clustermesh-apiserver
            dockerfile: ./enterprise/images/clustermesh-apiserver/Dockerfile
            base_image: ${{ needs.load-versions.outputs.ubi-micro }}
            postfix: ubi
            image_name: clustermesh-apiserver

          - name: gateway-api-controlplane
            dockerfile: ./enterprise/images/gateway-api-controlplane/Dockerfile
            # TODO: not available in Artifactory yet
            # renovate: datasource=docker
            base_image: ${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_DEV }}/cilium-runtime-cg:a495bcec15bc67c2cd0f18d7e5c90c127563e73c@sha256:a0d7f26ae39fbbf2e35d333fbd0dffd2439c79662b782b3129a673f38c8ff185
            postfix: ""
            image_name: gateway-api-controlplane
            digest_var_name: GATEWAY_API_CONTROLPLANE_DIGEST

          - name: gateway-api-controlplane
            dockerfile: ./enterprise/images/gateway-api-controlplane/Dockerfile
            base_image: ${{ needs.load-versions.outputs.ubi-micro }}
            postfix: ubi
            image_name: gateway-api-controlplane
            digest_var_name: GATEWAY_API_CONTROLPLANE_UBI_DIGEST

    steps:
      - name: Checkout main branch to access local actions
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false

      - name: Cleanup Disk space in runner
        uses: ./.github/actions/disk-cleanup

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to quay.io
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}

      - name: Login to Artifactory
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ vars.ARTIFACTORY_HOST }}
          username: ${{ vars.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Login to registry.redhat.io for pull of UBI images
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Getting image tag
        id: tag
        run: |
          tag=${GITHUB_REF##*/}
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"
          if [ -n "${{ matrix.postfix }}" ]; then
            image_name="${{ matrix.image_name }}-${{ matrix.postfix }}"
          else
            image_name="${{ matrix.image_name }}"
          fi
          echo "image_name=${image_name}" >> "$GITHUB_OUTPUT"
          echo "image_tag=quay.io/${{ env.QUAY_ORGANIZATION }}/${image_name}:${tag}" >> "$GITHUB_OUTPUT"
          echo "artifactory_image_tag=${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}/${image_name}:${tag}" >> "$GITHUB_OUTPUT"
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"

      - name: Checkout Source Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Release Build ${{ matrix.name }} UBI based
        id: docker_build_release_ubi
        shell: bash
        working-directory: ./enterprise/images
        run: |
          IMAGE_TAG=${{ steps.tag.outputs.tag }} \
          IMAGE_NAME=${{ steps.tag.outputs.image_name }} \
          BASE_IMAGE=${{ matrix.base_image }} \
          SUFFIX="" \
          REGISTRIES="quay.io/${{ env.QUAY_ORGANIZATION }} ${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}"\
          PUSH=true \
          RUNTIME_IMAGE=${{ matrix.base_image }} \
          UBI_IMAGE=${{ matrix.base_image }} \
          OPERATOR_VARIANT=${{ matrix.image_name }} \
          PLATFORMS=linux/amd64,linux/arm64 \
          EXTRA_ARGS="--provenance=false" \
          ENVOY_IMAGE=${{ matrix.envoy_image }} \
          make ${{ matrix.name }}-image

      - name: Release ${{ matrix.name }} digest
        id: docker_digest
        shell: bash
        run: |
          digest=$(images/scripts/get-image-digest.sh "${{ steps.tag.outputs.artifactory_image_tag }}")
          echo digest=${digest} >> $GITHUB_OUTPUT

      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Sign Container Images
        run: |
          cosign sign -y ${{ steps.tag.outputs.image_tag }}@${{ steps.docker_digest.outputs.digest }}
          cosign sign -y ${{ steps.tag.outputs.artifactory_image_tag }}@${{ steps.docker_digest.outputs.digest }}

      - name: Generate SBOM
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        with:
          artifact-name: sbom_${{ matrix.name }}_${{ matrix.postfix }}_${{ steps.tag.outputs.tag }}.spdx.json
          output-file: ./sbom_${{ matrix.name }}_${{ matrix.postfix }}_${{ steps.tag.outputs.tag }}.spdx.json
          image: ${{ steps.tag.outputs.artifactory_image_tag }}
          upload-release-assets: false

      - name: Attach SBOM attestation to container image
        run: |
          cosign attest -y --predicate sbom_${{ matrix.name }}_${{ matrix.postfix }}_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson ${{ steps.tag.outputs.image_tag }}
          cosign attest -y --predicate sbom_${{ matrix.name }}_${{ matrix.postfix }}_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson ${{ steps.tag.outputs.artifactory_image_tag }}

      - name: Image Release Digest
        shell: bash
        run: |
          mkdir -p image-digest/
          job_name=${{ matrix.name }}
          job_name_capital=${job_name^^}
          digest_var_name=${job_name_capital//-/_}_DIGEST
          if [[ -n "${{ matrix.digest_var_name }}" ]]; then
            digest_var_name="${{ matrix.digest_var_name }}"
          fi
          echo "${digest_var_name} := \"${{ steps.docker_digest.outputs.digest }}\"" > image-digest/makefile-digest.txt

          echo "### ${{ matrix.name }}" > image-digest/${{ matrix.name }}.txt
          echo "" >> image-digest/${{ matrix.name }}.txt
          echo "\`${{ steps.tag.outputs.artifactory_image_tag }}@${{ steps.docker_digest.outputs.digest }}\`" >> image-digest/${{ matrix.name }}.txt
          echo "" >> image-digest/${{ matrix.name }}.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: image-digest ${{ matrix.name }}-${{ matrix.postfix }}
          path: image-digest

  build-and-push-clife:
    timeout-minutes: 45
    name: Build and Push OLM Images
    environment: release
    runs-on: ubuntu-24.04
    needs: build-and-push

    steps:
      - name: Checkout main branch to access local actions
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false

      - name: Cleanup Disk space in runner
        uses: ./.github/actions/disk-cleanup

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Setup go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          cache: false
          # renovate: datasource=golang-version depName=go
          go-version: 1.26.4

      - name: Getting image tag
        id: tag
        run: |
          tag=${GITHUB_REF##*/}
          echo tag=$tag >> $GITHUB_OUTPUT
          echo image_tag_base=quay.io/${{ env.QUAY_ORGANIZATION }}/clife >> $GITHUB_OUTPUT
          echo artifactory_image_tag_base=${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}/clife >> $GITHUB_OUTPUT
          echo image_tag=quay.io/${{ env.QUAY_ORGANIZATION }}/clife:$tag >> $GITHUB_OUTPUT
          echo artifactory_image_tag=${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}/clife:$tag >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to quay.io
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}

      - name: Login to Artifactory
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ vars.ARTIFACTORY_HOST }}
          username: ${{ vars.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Login to registry.redhat.io for pull of UBI images
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Checkout Source Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: CLife Build and Push
        id: docker_build_clife
        shell: bash
        env:
          IMG: "${{ steps.tag.outputs.image_tag }}"
          CL_TAG: "${{ steps.tag.outputs.tag }}"
          CL_REGISTRY: "quay.io/${{ env.QUAY_ORGANIZATION }}"
          CL_IS_CI: false
        working-directory: ./enterprise/olm
        run: |
          make docker-buildx VERSION=${{ steps.tag.outputs.tag }}

      - name: CLife Build and Push Artifactory
        id: docker_build_clife_artifactory
        shell: bash
        env:
          IMG: "${{ steps.tag.outputs.artifactory_image_tag }}"
          CL_TAG: "${{ steps.tag.outputs.tag }}"
          CL_REGISTRY: "${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}"
          CL_IS_CI: false
        working-directory: ./enterprise/olm
        run: |
          make docker-buildx VERSION=${{ steps.tag.outputs.tag }}

      - name: OLM Bundle Build and Push
        working-directory: ./enterprise/olm
        env:
          CL_TAG: "${{ steps.tag.outputs.tag }}"
          CL_REGISTRY: "quay.io/${{ env.QUAY_ORGANIZATION }}"
          CL_IS_CI: false
          VERSION: "${{ steps.tag.outputs.tag }}"
          IMG: "${{ steps.tag.outputs.image_tag }}"
          IMAGE_TAG_BASE: "${{ steps.tag.outputs.image_tag_base }}"
        run: |
          VERSION="${VERSION#v}"
          make bundle
          make bundle-build
          make bundle-push

      - name: OLM Bundle Build and Push Artifactory
        working-directory: ./enterprise/olm
        env:
          CL_TAG: "${{ steps.tag.outputs.tag }}"
          CL_REGISTRY: "${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_PROD }}"
          CL_IS_CI: false
          VERSION: "${{ steps.tag.outputs.tag }}"
          IMG: "${{ steps.tag.outputs.artifactory_image_tag }}"
          IMAGE_TAG_BASE: "${{ steps.tag.outputs.artifactory_image_tag_base }}"
        run: |
          VERSION="${VERSION#v}"
          make bundle
          make bundle-build
          make bundle-push

      - name: Add bundle image to catalog and publish
        working-directory: ./enterprise/olm
        env:
          # renovate: datasource=docker depName=mikefarah/yq
          yq_version: 4.53.3
          # renovate: datasource=github-releases depName=operator-framework/operator-registry
          opm_version: 1.71.0
          VERSION: "${{ steps.tag.outputs.tag }}"
          CATALOG_TAG: "1.0.0"
          IMAGE_TAG_BASE: "${{ steps.tag.outputs.image_tag_base }}"
        run: |
          VERSION="${VERSION#v}"
          channel="${VERSION}"
          # separate channels per minor version
          channel=$(cut -d '.' -f 1,2 <<< "${channel}")
          if [[ ${VERSION} =~ "beta" ]]; then
            channel="${channel}-beta"
          fi
          make catalog-dev-build CHANNEL=${channel} DEFAULT_CHANNEL="1.17"
          make catalog-dev-push

      - name: Add bundle image to catalog and publish Artifactory
        working-directory: ./enterprise/olm
        env:
          # renovate: datasource=docker depName=mikefarah/yq
          yq_version: 4.53.3
          # renovate: datasource=github-releases depName=operator-framework/operator-registry
          opm_version: 1.71.0
          VERSION: "${{ steps.tag.outputs.tag }}"
          CATALOG_TAG: "1.0.0"
          IMAGE_TAG_BASE: "${{ steps.tag.outputs.artifactory_image_tag_base }}"
        run: |
          VERSION="${VERSION#v}"
          channel="${VERSION}"
          # separate channels per minor version
          channel=$(cut -d '.' -f 1,2 <<< "${channel}")
          if [[ ${VERSION} =~ "beta" ]]; then
            channel="${channel}-beta"
          fi
          make catalog-dev-build CHANNEL=${channel} DEFAULT_CHANNEL="1.19"
          make catalog-dev-push

      - name: Clife digests
        id: clife_docker_digests
        shell: bash
        run: |
          digest=$(images/scripts/get-image-digest.sh "${{ steps.tag.outputs.artifactory_image_tag }}")
          echo clife=${digest} >> $GITHUB_OUTPUT
          digest=$(images/scripts/get-image-digest.sh "${{ steps.tag.outputs.artifactory_image_tag_base }}-bundle:${{ steps.tag.outputs.tag }}")
          echo bundle=${digest} >> $GITHUB_OUTPUT
          digest=$(images/scripts/get-image-digest.sh "${{ steps.tag.outputs.artifactory_image_tag_base }}-catalog:1.0.0")
          echo catalog=${digest} >> $GITHUB_OUTPUT

      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Sign Container Images
        run: |
          cosign sign -y ${{ steps.tag.outputs.image_tag }}@${{ steps.clife_docker_digests.outputs.clife }}
          cosign sign -y ${{ steps.tag.outputs.artifactory_image_tag }}@${{ steps.clife_docker_digests.outputs.clife }}
          cosign sign -y ${{ steps.tag.outputs.image_tag_base }}-bundle:${{ steps.tag.outputs.tag }}@${{ steps.clife_docker_digests.outputs.bundle }}
          cosign sign -y ${{ steps.tag.outputs.artifactory_image_tag_base }}-bundle:${{ steps.tag.outputs.tag }}@${{ steps.clife_docker_digests.outputs.bundle }}
          cosign sign -y ${{ steps.tag.outputs.image_tag_base }}-catalog:1.0.0@${{ steps.clife_docker_digests.outputs.catalog }}
          cosign sign -y ${{ steps.tag.outputs.artifactory_image_tag_base }}-catalog:1.0.0@${{ steps.clife_docker_digests.outputs.catalog }}

      - name: Generate SBOM for CLife
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        with:
          artifact-name: sbom_clife_${{ steps.tag.outputs.tag }}.spdx.json
          output-file: ./sbom_clife_${{ steps.tag.outputs.tag }}.spdx.json
          image: ${{ steps.tag.outputs.artifactory_image_tag }}
          upload-release-assets: false

      - name: Attach SBOM attestation to CLife container image
        run: |
          cosign attest -y --predicate sbom_clife_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson ${{ steps.tag.outputs.image_tag }}
          cosign attest -y --predicate sbom_clife_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson ${{ steps.tag.outputs.artifactory_image_tag }}

      - name: Generate SBOM for the bundle
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        with:
          artifact-name: sbom_clife_bundle_${{ steps.tag.outputs.tag }}.spdx.json
          output-file: ./sbom_clife_bundle_${{ steps.tag.outputs.tag }}.spdx.json
          image: "${{ steps.tag.outputs.artifactory_image_tag_base }}-bundle:${{ steps.tag.outputs.tag }}"
          upload-release-assets: false

      - name: Attach SBOM attestation to the bundle container image
        run: |
          cosign attest -y --predicate sbom_clife_bundle_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson ${{ steps.tag.outputs.image_tag_base }}-bundle:${{ steps.tag.outputs.tag }}
          cosign attest -y --predicate sbom_clife_bundle_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson ${{ steps.tag.outputs.artifactory_image_tag_base }}-bundle:${{ steps.tag.outputs.tag }}

      - name: Generate SBOM for the catalog
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        with:
          artifact-name: sbom_clife_catalog_${{ steps.tag.outputs.tag }}.spdx.json
          output-file: ./sbom_clife_catalog_${{ steps.tag.outputs.tag }}.spdx.json
          image: "${{ steps.tag.outputs.artifactory_image_tag_base }}-catalog:1.0.0"
          upload-release-assets: false

      - name: Attach SBOM attestation to the catalog container image
        run: |
          cosign attest -y --predicate sbom_clife_catalog_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson ${{ steps.tag.outputs.image_tag_base }}-catalog:1.0.0
          cosign attest -y --predicate sbom_clife_catalog_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson ${{ steps.tag.outputs.artifactory_image_tag_base }}-catalog:1.0.0

      - name: Image Release Digests
        shell: bash
        run: |
          mkdir -p image-digest/
          echo "### clife" > image-digest/clife.txt
          echo "" >> image-digest/clife.txt
          echo "\`${{ steps.tag.outputs.artifactory_image_tag }}@${{ steps.clife_docker_digests.outputs.clife }}\`" >> image-digest/clife.txt
          echo "" >> image-digest/clife.txt

          echo "### clife bundle" > image-digest/clife-bundle.txt
          echo "" >> image-digest/clife-bundle.txt
          echo "\`${{ steps.tag.outputs.artifactory_image_tag_base }}-bundle:${{ steps.tag.outputs.tag }}@${{ steps.clife_docker_digests.outputs.bundle }}\`" >> image-digest/clife-bundle.txt
          echo "" >> image-digest/clife-bundle.txt

          echo "### clife catalog" > image-digest/clife-catalog.txt
          echo "" >> image-digest/clife-catalog.txt
          echo "\`${{ steps.tag.outputs.artifactory_image_tag_base }}-catalog:1.0.0@${{ steps.clife_docker_digests.outputs.catalog }}\`" >> image-digest/clife-catalog.txt
          echo "" >> image-digest/clife-catalog.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: image-digest clife
          path: image-digest

  image-digests:
    name: Display Digests
    runs-on: ubuntu-24.04
    needs:
      [build-and-push-external-images, build-and-push, build-and-push-clife]

    steps:
      - name: Prepare image digests download
        shell: bash
        run: |
          mkdir -p image-digest/

      - name: Download digests of all images built
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: image-digest/
          pattern: "*image-digest *"

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          find -type f | sort | xargs -d '\n' cat
