name: Build images external to isovalent/cilium

# Any change in triggers needs to be reflected in the concurrency group.
on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      image-name:
        required: true
        type: string
      version-path:
        required: false
        type: string
        default: "true"
        description: "Path to the version field in values.yaml. For OSS images the version is taken from Makefile.values and this parameter should be left empty."
      docker-context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      base-image:
        required: true
        type: string

permissions: read-all

jobs:
  check-changes:
    name: Deduce changes
    runs-on: ubuntu-24.04
    outputs:
      rebuild: ${{ steps.check-changes.outputs.rebuild }}
      repo: ${{ steps.check-changes.outputs.repo }}
      version: ${{ steps.check-changes.outputs.version }}
      digest: ${{ steps.check-changes.outputs.digest }}

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.after }}
          persist-credentials: false
          fetch-depth: 0

      - name: Check ${{ inputs.component }} changes
        id: check-changes
        run: |
          if [ -z "${{ inputs.version-path }}" ]; then
            echo "repo=$(cat install/kubernetes/Makefile.values| grep ${{ inputs.component }}_REPO | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
            version=$(cat install/kubernetes/Makefile.values| grep ${{ inputs.component }}_VERSION | awk -F '=' '{print $2}')
            echo "version=${version}" >> $GITHUB_OUTPUT
            echo "digest=$(cat install/kubernetes/Makefile.values| grep ${{ inputs.component }}_DIGEST | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
          else
            version="$(yq '${{ inputs.version-path }}' install/kubernetes/cilium/values.yaml)"
            echo "version=${version}" >> $GITHUB_OUTPUT
          fi
          # Don't rebuild if the image already exists
          if docker manifest inspect ${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_DEV }}/${{ inputs.image-name }}:${version} && docker manifest inspect quay.io/isovalent-dev/${{ inputs.image-name }}:${version}; then
            echo "Image already exist!"
            echo "rebuild=false" >> $GITHUB_OUTPUT
          else
            echo "rebuild=true" >> $GITHUB_OUTPUT
          fi

  build-push-image:
    needs: [check-changes]
    if: ${{ needs.check-changes.outputs.rebuild == 'true' }}
    name: Build and push image
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.push.after }}
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to quay.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_CI }}
          password: ${{ secrets.QUAY_PASSWORD_CI }}

      - name: Login to Artifactory
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ vars.ARTIFACTORY_HOST }}
          username: ${{ vars.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Login to registry.redhat.io for pulling images
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Build and push ${{ inputs.component }} image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        id: docker_build_release
        with:
          context: ${{ inputs.docker-context }}
          file: ${{ inputs.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          # The purpose of the second tag is to ensure that the image can be pulled by digest
          # even if there is a race condition with another run building and pushing the image with
          # the same primary tag.
          tags: |
            quay.io/isovalent-dev/${{ inputs.image-name }}:${{ needs.check-changes.outputs.version }}
            quay.io/isovalent-dev/${{ inputs.image-name }}:${{ github.run_id }}
            ${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_DEV }}/${{ inputs.image-name }}:${{ needs.check-changes.outputs.version }}
            ${{ vars.ARTIFACTORY_HOST }}/${{ vars.ARTIFACTORY_ORGANIZATION_DEV }}/${{ inputs.image-name }}:${{ github.run_id }}
          build-args: |
            BASE_IMAGE=${{ inputs.base-image }}
            UPSTREAM_VERSION=${{ needs.check-changes.outputs.version }}
            UPSTREAM_IMAGE=${{ needs.check-changes.outputs.repo }}:${{ needs.check-changes.outputs.version }}@${{ needs.check-changes.outputs.digest }}
            VERSION=${{ needs.check-changes.outputs.version }}

      - name: Image Release Digests
        shell: bash
        run: |
          mkdir -p image-digest/
          echo "## ${{ inputs.image-name }}" > image-digest/${{ inputs.image-name }}.txt
          echo "" >> image-digest/${{ inputs.image-name }}.txt
          echo "\`${{ vars.ARTIFACTORY_HOST }}}/${{ vars.ARTIFACTORY_ORGANIZATION_DEV }}/${{ inputs.image-name }}:${{ needs.check-changes.outputs.version }}@${{ steps.docker_build_release.outputs.digest }}\`" >> image-digest/${{ inputs.image-name }}.txt
          echo "" >> image-digest/${{ inputs.image-name }}.txt

      - name: Upload artifact digests runtime
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: image-digest ${{ inputs.image-name }}
          path: image-digest

  image-digests:
    name: Display Digests
    runs-on: ubuntu-24.04
    needs: build-push-image
    steps:
      - name: Downloading Image Digests
        shell: bash
        run: |
          mkdir -p image-digest/

      - name: Download digests of all images built
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: image-digest/
          pattern: "*image-digest *"

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          find -type f | sort | xargs -d '\n' cat
